/**
 * Generates supabase/seed.sql from the original blog posts in
 * supabase/blog-posts.seed.ts.
 *
 *   node supabase/generate-seed.ts
 *
 * The SQL upserts on slug, so running it again overwrites those posts.
 */
import { writeFileSync } from "node:fs";
import { BLOG_POSTS } from "./blog-posts.seed.ts";

const text = (v: string | undefined | null) =>
  v == null ? "null" : `'${v.replace(/'/g, "''")}'`;
const json = (v: unknown) =>
  v == null ? "null" : `${text(JSON.stringify(v))}::jsonb`;
const num = (v: number | undefined | null) => (v == null ? "null" : String(v));

const columns = [
  "slug", "title", "subtitle", "excerpt", "category", "read_time",
  "published_at", "updated_at", "author", "hero_sketch", "keywords",
  "takeaways", "sections", "tags", "related_slugs", "cross_page_links",
  "faq", "featured", "popularity_score", "translations", "sort_order",
  "published",
];

const rows = BLOG_POSTS.map((p, i) =>
  [
    text(p.slug), text(p.title), text(p.subtitle), text(p.excerpt),
    text(p.category), num(p.readTime), text(p.publishedAt),
    text(p.updatedAt), json(p.author), text(p.heroSketch), json(p.keywords),
    json(p.takeaways), json(p.sections), json(p.tags), json(p.relatedSlugs),
    json(p.crossPageLinks), json(p.faq), String(!!p.featured),
    num(p.popularityScore), json(p.translations), String(i), "true",
  ].join(",\n  ")
);

const sql = `-- Generated by supabase/generate-seed.ts — ${BLOG_POSTS.length} posts.
-- Run after schema.sql in the Supabase SQL editor.

insert into public.blog_posts (
  ${columns.join(", ")}
) values
(
  ${rows.join("\n),\n(\n  ")}
)
on conflict (slug) do update set
  ${columns.filter((c) => c !== "slug").map((c) => `${c} = excluded.${c}`).join(",\n  ")};
`;

writeFileSync(new URL("./seed.sql", import.meta.url), sql);
console.log(`Wrote supabase/seed.sql with ${BLOG_POSTS.length} posts.`);
