import type { Locale } from "@/lib/i18n";
import { SERVICES_EN, type CapabilityId, type ServicesCopy } from "./services-copy";

type CapabilityText = [name: string, problem: string, build: string, how: string, outcome: string, flow: [string,string,string]];
type PageTranslation = Omit<ServicesCopy,"capabilities"> & { capabilities: Record<CapabilityId,CapabilityText> };

const translations: Record<Exclude<Locale,"en">,PageTranslation> = {
  es: {
    meta: "Software, agentes de IA, automatización, ERP e IoT industrial conectados alrededor de tu negocio.", hero: ["Capacidades individuales.","Un negocio conectado."], intro: "Creamos el software, las conexiones y la inteligencia que convierten procesos dispersos en un sistema que funciona alrededor de tu negocio.", explore: "Explora el ecosistema", heroNote: "De la primera señal a la siguiente acción útil.", story: ["Problema de negocio","Sistema conectado","Automatización","Inteligencia","Resultado de negocio"], chapters: ["El ecosistema de servicios","IA y automatización","Conectividad industrial","Nuestros sistemas","Diseñado para ti","El siguiente paso"], ecosystem: ["Empieza por el obstáculo.","Conecta las capacidades adecuadas."], ecosystemIntro: "Descubre qué cambia cada capacidad. Su valor crece cuando trabajan juntas.", selectHint: "Elige una capacidad", detailLabels: ["El problema","Qué construimos","Cómo funciona","Qué cambia"], diagramLabel: "Un sistema conectado en la práctica",
    capabilities: {
      ai: ["IA y agentes inteligentes","Tu equipo repite búsquedas, análisis y preparación de información.","Asistentes y agentes con contexto y herramientas autorizadas.","Una petición conecta datos, APIs permitidas y revisión humana.","Respuestas útiles y acciones preparadas en el trabajo diario.",["Pregunta de negocio","Contexto y agente IA","Acción revisada"]],
      automation: ["Automatización de procesos","Seguimientos, aprobaciones y traspasos dependen de recordatorios manuales.","Workflows, automatizaciones de CRM y procesos de aprobación.","Un evento inicia una secuencia con responsables para las excepciones.","Menos seguimiento manual y trabajo que avanza.",["Evento de negocio","Reglas y workflow","Tarea completada"]],
      erp: ["ERP y sistemas de negocio","Compras, inventario y finanzas manejan versiones distintas.","OperateOS: módulos ERP, paneles y portales de proveedores o clientes.","Registros compartidos conectan departamentos, permisos y aprobaciones.","Una visión operativa desde el pedido hasta la entrega.",["Pedidos e inventario","OperateOS / ERP","Operación conectada"]],
      industrial: ["IoT industrial","Los eventos de las máquinas no llegan a las decisiones.","Integraciones de sensores, conectividad y monitorización operativa.","Las señales pasan por una conexión local hacia software y workflows.","Una planta visible y preparada para actuar.",["Señal de máquina","IoT y datos","Acción del operador"]],
      software: ["Software a medida","Tu proceso supera las hojas de cálculo y las herramientas estándar.","Aplicaciones internas, herramientas de campo y software operativo.","Roles, datos y reglas se convierten en una aplicación mantenible.","Una herramienta adaptada al trabajo real de tu equipo.",["Tu proceso","Software a medida","Trabajo más sencillo"]],
      integrations: ["APIs e integraciones","Las personas copian información entre aplicaciones aisladas.","Conexiones API e intercambios de datos entre sistemas existentes.","Mapear, validar y dirigir la información con control de excepciones.","Menos duplicación e información coherente.",["Herramientas existentes","APIs e integración","Contexto compartido"]],
      data: ["Datos y analítica","Los informes llegan tarde y muestran una visión parcial.","Datos conectados, paneles operativos e informes de gestión.","Unir fuentes, definir medidas y mostrar señales relevantes.","Mayor claridad sobre el rendimiento y la siguiente decisión.",["Datos dispersos","Analítica y paneles","Decisión informada"]],
      platforms: ["Plataformas digitales","Las experiencias se interrumpen entre herramientas separadas.","Plataformas web, portales de autoservicio y experiencias conectadas.","La experiencia del usuario se une a CRM, ERP y workflows.","Un recorrido fluido con la operación conectada detrás.",["Necesidad del cliente","Plataforma y sistemas","Experiencia conectada"]],
    },
    aiTitle: ["Inteligencia con contexto.","Automatización con control."], aiIntro: "Un modelo necesita información relevante, herramientas definidas y un camino claro de la recomendación a la acción.", aiLabels: ["Petición de negocio","Agente IA","Herramientas autorizadas","Revisión humana","Acción de negocio"], aiNotes: ["Una pregunta o tarea","Comprende el contexto","MCP + APIs","Aprobaciones necesarias","Un resultado registrado"], modelNote: "OpenAI · Claude · Grok / xAI — elegidos según la tarea", aiFoot: "ERP, IoT y analítica aportan contexto. Los workflows llevan la acción. Tus permisos marcan el límite.", industrialTitle: ["De la planta industrial","a la siguiente decisión."], industrialIntro: "Conecta la operación física con el software del negocio. Una señal es útil cuando alguien puede actuar.", industrialSteps: ["Máquinas","Sensores","Datos","Sistemas","Automatización","Inteligencia","Acción"], industrialNotes: [{title:"Capturar el evento",body:"Reunir el estado de los equipos y las señales de producción."},{title:"Añadir contexto",body:"Vincular el evento con una orden, inventario o mantenimiento."},{title:"Habilitar la respuesta",body:"Avisar al operador, preparar una tarea y registrar la acción."}], industrialFoot: "Arquitectura ilustrativa. Las conexiones dependen de tus equipos, protocolos e infraestructura.", catalogTitle: ["Las capacidades se conectan.","El alcance queda claro."], catalogIntro: "Nuestros sistemas de servicio ofrecen un punto de partida. Explora los entregables y combina lo que necesita tu negocio.", deliverables: "Incluido en el sistema", investment: "Inversión publicada", discuss: "Hablar de este sistema", pathTitle: ["Tu negocio es el plano.","Conectamos las piezas."], pathIntro: "Empieza por una limitación. Construye un sistema útil. Amplíalo con tu negocio.", path: ["Tu negocio","Encontrar el obstáculo","Diseñar el sistema","Conectar los datos","Automatizar operaciones","Añadir inteligencia","Escalar"], cta: ["¿Qué podría funcionar mejor?","Empecemos por ahí."], ctaIntro: "Cuéntanos el proceso, la herramienta desconectada o la idea. Aclararemos el siguiente paso.", audit: "Auditoría gratuita de {minutes} minutos. Diagnóstico escrito. Un punto de partida práctico.", aboutLink: "Cómo pensamos y trabajamos", pause:"Pausar movimiento",resume:"Reanudar movimiento",reduced:"Movimiento reducido",
  },
  fr: {
    meta: "Logiciels, agents IA, automatisation, ERP et IoT industriel connectés autour de votre entreprise.", hero:["Des capacités distinctes.","Une entreprise connectée."],intro:"Nous créons les logiciels, les connexions et l’intelligence qui transforment des processus dispersés en un système adapté à votre activité.",explore:"Explorer l’écosystème",heroNote:"Du premier signal à la prochaine action utile.",story:["Problème métier","Système connecté","Automatisation","Intelligence","Résultat métier"],chapters:["L’écosystème de services","IA et automatisation","Connectivité industrielle","Nos systèmes","Conçu pour vous","La prochaine étape"],ecosystem:["Partir du blocage.","Relier les bonnes capacités."],ecosystemIntro:"Découvrez ce que chaque capacité change. Leur valeur vient de leur collaboration.",selectHint:"Choisir une capacité",detailLabels:["Le problème","Ce que nous créons","Le fonctionnement","Ce qui change"],diagramLabel:"Un système connecté en pratique",
    capabilities:{
      ai:["IA et agents intelligents","L’équipe répète recherches, analyses et préparation d’informations.","Des assistants et agents avec contexte et outils autorisés.","Une demande relie données utiles, APIs permises et contrôle humain.","Des réponses utiles et des actions préparées au quotidien.",["Question métier","Contexte et agent IA","Action vérifiée"]],
      automation:["Automatisation métier","Relances, validations et passages de relais restent manuels.","Des workflows, automatisations CRM et circuits de validation.","Un événement lance une séquence avec gestion des exceptions.","Moins de relances et un travail qui avance.",["Événement métier","Règles et workflow","Tâche terminée"]],
      erp:["ERP et systèmes métier","Achats, stocks et finance utilisent des versions différentes.","OperateOS : modules ERP, tableaux de bord et portails.","Des dossiers partagés relient services, permissions et validations.","Une vision commune de la commande à la livraison.",["Commandes et stocks","OperateOS / ERP","Opération connectée"]],
      industrial:["IoT industriel","Les événements des machines restent éloignés des décisions.","Des intégrations de capteurs et du suivi opérationnel.","Les signaux rejoignent logiciels et workflows via une passerelle locale.","Un atelier visible et des actions possibles.",["Signal machine","IoT et données","Action opérateur"]],
      software:["Logiciels sur mesure","Votre processus dépasse les tableurs et outils standards.","Des applications internes, outils terrain et logiciels métier.","Rôles, données et règles deviennent une application maintenable.","Un outil adapté au travail réel de votre équipe.",["Votre processus","Logiciel sur mesure","Travail simplifié"]],
      integrations:["APIs et intégrations","Les personnes recopient des informations entre applications isolées.","Des connexions API et échanges entre systèmes existants.","Mapper, valider et acheminer les données avec gestion des exceptions.","Moins de ressaisie et des informations cohérentes.",["Outils existants","APIs et intégration","Contexte partagé"]],
      data:["Données et analytique","Les rapports arrivent tard et restent fragmentaires.","Des jeux de données connectés, tableaux de bord et rapports.","Réunir les sources, définir les mesures et montrer les signaux utiles.","Une meilleure visibilité pour la prochaine décision.",["Données dispersées","Analytique et tableaux","Décision éclairée"]],
      platforms:["Plateformes numériques","Les parcours se coupent entre outils séparés.","Des plateformes web, portails libre-service et expériences connectées.","Relier l’expérience utilisateur aux CRM, ERP et workflows.","Un parcours fluide avec les opérations reliées en arrière-plan.",["Besoin client","Plateforme et systèmes","Expérience connectée"]],
    },
    aiTitle:["Une intelligence contextualisée.","Une automatisation maîtrisée."],aiIntro:"Un modèle a besoin d’informations pertinentes, d’outils définis et d’un chemin clair vers l’action.",aiLabels:["Demande métier","Agent IA","Outils autorisés","Contrôle humain","Action métier"],aiNotes:["Une question ou tâche","Comprend le contexte","MCP + APIs","Validations nécessaires","Un résultat enregistré"],modelNote:"OpenAI · Claude · Grok / xAI — choisis selon la tâche",aiFoot:"ERP, IoT et analytique apportent le contexte. Les workflows portent l’action. Vos permissions fixent les limites.",industrialTitle:["De l’atelier","à la prochaine décision."],industrialIntro:"Reliez l’activité physique aux logiciels métier. Un signal devient utile lorsqu’une personne peut agir.",industrialSteps:["Machines","Capteurs","Données","Systèmes","Automatisation","Intelligence","Action"],industrialNotes:[{title:"Capter l’événement",body:"Partager l’état des équipements et les signaux de production."},{title:"Ajouter le contexte",body:"Relier l’événement à un ordre, un stock ou une maintenance."},{title:"Permettre la réponse",body:"Alerter l’opérateur, préparer une tâche et enregistrer l’action."}],industrialFoot:"Architecture illustrative. Les connexions dépendent de vos équipements, protocoles et infrastructures.",catalogTitle:["Les capacités se relient.","Le périmètre reste clair."],catalogIntro:"Nos offres constituent un point de départ concret. Explorez les livrables et adaptez leur combinaison à votre activité.",deliverables:"Inclus dans le système",investment:"Investissement publié",discuss:"Parler de ce système",pathTitle:["Votre métier donne le plan.","Nous relions les éléments."],pathIntro:"Commencez par une contrainte. Créez un système utile. Développez-le avec votre activité.",path:["Votre entreprise","Trouver le blocage","Concevoir le système","Relier les données","Automatiser","Ajouter l’intelligence","Développer"],cta:["Que peut-on améliorer ?","Construisons à partir de là."],ctaIntro:"Parlez-nous du processus, de l’outil isolé ou de l’idée. Nous clarifierons la prochaine étape.",audit:"Audit gratuit de {minutes} minutes. Diagnostic écrit. Point de départ concret.",aboutLink:"Notre réflexion et notre méthode",pause:"Suspendre le mouvement",resume:"Reprendre le mouvement",reduced:"Mouvement réduit",
  },
  de: {
    meta:"Verbundene Software, KI-Agenten, Automatisierung, ERP und industrielles IoT für Ihr Unternehmen.",hero:["Einzelne Fähigkeiten.","Ein verbundenes Unternehmen."],intro:"Wir entwickeln Software, Verbindungen und Intelligenz, die verstreute Prozesse zu einem funktionierenden System machen – passend zu Ihrem Betrieb.",explore:"Das Ökosystem entdecken",heroNote:"Vom ersten Signal zur nächsten sinnvollen Handlung.",story:["Geschäftsproblem","Verbundenes System","Automatisierung","Intelligenz","Geschäftsergebnis"],chapters:["Das Service-Ökosystem","KI und Automatisierung","Industrielle Vernetzung","Unsere Systeme","Für Ihr Unternehmen","Der nächste Schritt"],ecosystem:["Beim Engpass beginnen.","Die richtigen Fähigkeiten verbinden."],ecosystemIntro:"Entdecken Sie, was jede Fähigkeit verändert. Der Wert entsteht im Zusammenspiel.",selectHint:"Eine Fähigkeit auswählen",detailLabels:["Das Problem","Was wir entwickeln","Wie es funktioniert","Was sich ändert"],diagramLabel:"Ein verbundenes System in der Praxis",
    capabilities:{
      ai:["KI und intelligente Agenten","Ihr Team wiederholt Recherche, Analyse und Informationsaufbereitung.","Assistenten und Agenten mit freigegebenem Kontext und Werkzeugen.","Eine Anfrage verbindet relevante Daten, erlaubte APIs und menschliche Prüfung.","Nützliche Antworten und vorbereitete Aktionen im Alltag.",["Geschäftliche Frage","Kontext und KI-Agent","Geprüfte Aktion"]],
      automation:["Geschäftsautomatisierung","Nachfassen, Freigaben und Übergaben hängen von Erinnerungen ab.","Workflows, CRM-Automatisierungen und Freigabeprozesse.","Ein Ereignis startet eine Abfolge mit geregelter Ausnahmebehandlung.","Weniger Nachfragen und Arbeit, die weiterläuft.",["Geschäftsereignis","Regeln und Workflow","Erledigte Aufgabe"]],
      erp:["ERP und Geschäftssysteme","Einkauf, Bestand und Finanzen nutzen unterschiedliche Datenstände.","OperateOS: ERP-Module, Dashboards und Lieferanten- oder Kundenportale.","Gemeinsame Datensätze verbinden Abteilungen, Rechte und Freigaben.","Ein gemeinsamer Blick vom Auftrag bis zur Lieferung.",["Aufträge und Bestand","OperateOS / ERP","Verbundener Betrieb"]],
      industrial:["Industrielles IoT","Maschinensignale erreichen die Geschäftsentscheidungen nicht.","Sensorintegration, Gerätevernetzung und Betriebsüberwachung.","Signale gelangen über eine lokale Anbindung in Software und Workflows.","Die Fertigung wird sichtbar und handlungsfähig.",["Maschinensignal","IoT und Daten","Aktion des Teams"]],
      software:["Individuelle Software","Ihr Prozess überfordert Tabellen und Standardwerkzeuge.","Interne Anwendungen, Außendienstwerkzeuge und Betriebssoftware.","Rollen, Daten und Regeln werden zu einer wartbaren Anwendung.","Ein Werkzeug, das zur tatsächlichen Arbeit passt.",["Ihr Prozess","Individuelle Software","Einfachere Arbeit"]],
      integrations:["APIs und Integrationen","Menschen kopieren Informationen zwischen getrennten Anwendungen.","API-Verbindungen und Datenaustausch zwischen bestehenden Systemen.","Daten zuordnen, prüfen und mit klarer Fehlerbehandlung weiterleiten.","Weniger Mehrfacheingaben und konsistente Informationen.",["Bestehende Werkzeuge","APIs und Integration","Gemeinsamer Kontext"]],
      data:["Daten und Analysen","Berichte kommen spät und zeigen nur Ausschnitte.","Verbundene Datenbestände, Betriebsdashboards und Managementberichte.","Quellen verbinden, Kennzahlen definieren und relevante Signale zeigen.","Mehr Klarheit für die nächste Entscheidung.",["Verteilte Daten","Analysen und Dashboards","Fundierte Entscheidung"]],
      platforms:["Digitale Plattformen","Nutzerwege brechen zwischen getrennten Werkzeugen ab.","Webplattformen, Selbstbedienungsportale und verbundene Erlebnisse.","Die Benutzeroberfläche wird mit CRM, ERP und Workflows verbunden.","Ein reibungsloser Weg mit verbundenem Betrieb im Hintergrund.",["Kundenbedarf","Plattform und Systeme","Verbundenes Erlebnis"]],
    },
    aiTitle:["Intelligenz mit Kontext.","Automatisierung mit Kontrolle."],aiIntro:"Ein Modell braucht relevante Informationen, definierte Werkzeuge und einen klaren Weg von der Empfehlung zur Handlung.",aiLabels:["Geschäftliche Anfrage","KI-Agent","Freigegebene Werkzeuge","Menschliche Prüfung","Geschäftliche Aktion"],aiNotes:["Eine Frage oder Aufgabe","Versteht den Kontext","MCP + APIs","Nötige Freigaben","Erfasstes Ergebnis"],modelNote:"OpenAI · Claude · Grok / xAI — passend zur Aufgabe",aiFoot:"ERP, IoT und Analysen liefern Kontext. Workflows tragen die Aktion. Ihre Berechtigungen setzen die Grenzen.",industrialTitle:["Von der Fertigung","zur nächsten Entscheidung."],industrialIntro:"Verbinden Sie den physischen Betrieb mit der Unternehmenssoftware. Ein Signal hilft, wenn jemand darauf reagieren kann.",industrialSteps:["Maschinen","Sensoren","Daten","Systeme","Automatisierung","Intelligenz","Aktion"],industrialNotes:[{title:"Das Ereignis erfassen",body:"Gerätezustände und Produktionssignale gemeinsam sichtbar machen."},{title:"Kontext ergänzen",body:"Das Ereignis mit Auftrag, Bestand oder Wartungsprozess verbinden."},{title:"Die Reaktion ermöglichen",body:"Das Team informieren, eine Aufgabe vorbereiten und die Aktion erfassen."}],industrialFoot:"Beispielarchitektur. Verbindungen hängen von Geräten, Protokollen und Infrastruktur ab.",catalogTitle:["Fähigkeiten verbinden sich.","Der Umfang bleibt klar."],catalogIntro:"Unsere bestehenden Angebote bieten einen praktischen Einstieg. Erkunden Sie die Leistungen und kombinieren Sie sie passend zum Betrieb.",deliverables:"Im System enthalten",investment:"Veröffentlichter Preisrahmen",discuss:"Dieses System besprechen",pathTitle:["Ihr Geschäft ist der Bauplan.","Wir verbinden die Teile."],pathIntro:"Mit einem Engpass anfangen. Ein nützliches System bauen. Mit dem Betrieb wachsen.",path:["Ihr Unternehmen","Engpass finden","System entwerfen","Daten verbinden","Abläufe automatisieren","Intelligenz ergänzen","Skalieren"],cta:["Was könnte besser laufen?","Dort setzen wir an."],ctaIntro:"Bringen Sie den Prozess, das isolierte Werkzeug oder die Idee mit. Wir klären den nächsten Schritt.",audit:"Kostenlose Analyse: {minutes} Minuten. Schriftliche Diagnose. Praktischer Einstieg.",aboutLink:"Wie wir denken und arbeiten",pause:"Bewegung pausieren",resume:"Bewegung fortsetzen",reduced:"Reduzierte Bewegung",
  },
  ar: {
    meta:"برمجيات ووكلاء ذكاء اصطناعي وأتمتة وأنظمة ERP وإنترنت أشياء صناعي مترابطة حول أعمالك.",hero:["قدرات متعددة.","أعمال مترابطة."],intro:"نبني البرمجيات والروابط والذكاء التي تحوّل العمليات المتفرقة إلى نظام يعمل وفق طبيعة أعمالك.",explore:"استكشف المنظومة",heroNote:"من أول إشارة إلى الإجراء المفيد التالي.",story:["مشكلة الأعمال","نظام مترابط","الأتمتة","الذكاء","نتيجة الأعمال"],chapters:["منظومة الخدمات","الذكاء الاصطناعي والأتمتة","الربط الصناعي","أنظمة خدماتنا","مصمم لأعمالك","الخطوة التالية"],ecosystem:["ابدأ بالعائق.","اربط القدرات المناسبة."],ecosystemIntro:"اكتشف ما تغيّره كل قدرة. القيمة الحقيقية تأتي من عملها معاً.",selectHint:"اختر قدرة",detailLabels:["المشكلة","ما نبنيه","كيف يعمل","ما الذي يتغير"],diagramLabel:"نظام مترابط في التطبيق",
    capabilities:{
      ai:["الذكاء الاصطناعي والوكلاء","يكرر فريقك البحث والتحليل وإعداد المعلومات.","مساعدون ووكلاء بسياق أعمال وأدوات معتمدة.","يرتبط الطلب ببيانات مناسبة وواجهات مسموحة ومراجعة بشرية.","إجابات مفيدة وإجراءات جاهزة ضمن العمل اليومي.",["سؤال أعمال","سياق ووكيل ذكي","إجراء مُراجع"]],
      automation:["أتمتة الأعمال والتدفقات","المتابعات والموافقات والتسليم تعتمد على التذكير اليدوي.","تدفقات عمل وأتمتة CRM ومسارات موافقات.","يبدأ الحدث تسلسلاً محدداً مع توجيه الاستثناءات للمسؤول.","متابعة أقل وعمل يتقدم بمسؤوليات واضحة.",["حدث أعمال","قواعد وتدفق","مهمة مكتملة"]],
      erp:["ERP وأنظمة الأعمال","المشتريات والمخزون والمالية تستخدم نسخاً مختلفة من البيانات.","OperateOS: وحدات ERP ولوحات وبوابات للموردين والعملاء.","تربط السجلات المشتركة الأقسام والصلاحيات والموافقات.","رؤية واحدة من الطلب إلى التسليم.",["طلبات ومخزون","OperateOS / ERP","عمليات مترابطة"]],
      industrial:["إنترنت الأشياء الصناعي","أحداث الآلات لا تصل إلى قرارات الأعمال.","تكامل مستشعرات وربط معدات ومراقبة تشغيلية.","تنتقل الإشارات عبر اتصال محلي إلى البرامج وتدفقات العمل.","أرض مصنع مرئية وقابلة للاستجابة.",["إشارة آلة","IoT وبيانات","إجراء المشغّل"]],
      software:["برمجيات مخصصة","تجاوزت عملياتك الجداول وحدود الأدوات الجاهزة.","تطبيقات داخلية وأدوات ميدانية وبرمجيات تشغيلية.","تتحول الأدوار والبيانات والقواعد إلى تطبيق قابل للصيانة.","أداة تناسب العمل الفعلي لفريقك.",["عمليتك","برمجيات مخصصة","عمل أبسط"]],
      integrations:["APIs وتكامل الأنظمة","ينسخ الأشخاص المعلومات بين تطبيقات منفصلة.","اتصالات API وتبادل بيانات بين الأنظمة القائمة.","تعيين المعلومات والتحقق منها وتوجيهها مع إدارة الاستثناءات.","إعادة إدخال أقل ومعلومات متسقة.",["أدوات قائمة","APIs وتكامل","سياق مشترك"]],
      data:["البيانات والتحليلات","التقارير متأخرة والقرارات تعتمد على صورة جزئية.","بيانات مترابطة ولوحات تشغيلية وتقارير إدارية.","جمع المصادر وتحديد المقاييس وإظهار الإشارات المهمة.","رؤية أوضح للأداء والقرار التالي.",["بيانات متفرقة","تحليلات ولوحات","قرار مستنير"]],
      platforms:["منصات رقمية مخصصة","تنقطع رحلة المستخدم عند حدود الأدوات المنفصلة.","منصات ويب وبوابات خدمة ذاتية وتجارب مترابطة.","نربط تجربة المستخدم بأنظمة CRM وERP وتدفقات العمل.","رحلة أسلس وخلفها عمليات مترابطة.",["حاجة العميل","منصة وأنظمة","تجربة مترابطة"]],
    },
    aiTitle:["ذكاء مع سياق.","أتمتة مع تحكّم."],aiIntro:"يحتاج النموذج إلى معلومات مناسبة وأدوات محددة ومسار واضح من التوصية إلى الإجراء.",aiLabels:["طلب أعمال","وكيل ذكي","أدوات معتمدة","مراجعة بشرية","إجراء أعمال"],aiNotes:["سؤال أو مهمة","يفهم السياق","MCP + APIs","موافقات عند الحاجة","نتيجة مسجلة"],modelNote:"OpenAI · Claude · Grok / xAI — الاختيار حسب المهمة",aiFoot:"توفر ERP وIoT والتحليلات السياق. تحمل التدفقات الإجراء. تحدد صلاحياتك الحدود.",industrialTitle:["من أرض المصنع","إلى القرار التالي."],industrialIntro:"اربط التشغيل المادي ببرمجيات الأعمال. تصبح الإشارة مفيدة عندما يستطيع شخص التصرف.",industrialSteps:["آلات","مستشعرات","بيانات","أنظمة","أتمتة","ذكاء","إجراء"],industrialNotes:[{title:"التقاط الحدث",body:"جمع حالة المعدات وإشارات الإنتاج في رؤية مشتركة."},{title:"إضافة السياق",body:"ربط الحدث بأمر عمل أو مخزون أو مسار صيانة."},{title:"تمكين الاستجابة",body:"إشعار المشغّل وتجهيز مهمة وتسجيل الإجراء التالي."}],industrialFoot:"بنية توضيحية. تعتمد الروابط على معداتك وبروتوكولاتك وبنيتك التحتية.",catalogTitle:["تترابط القدرات.","ويبقى النطاق واضحاً."],catalogIntro:"توفر أنظمة خدماتنا نقطة بداية عملية. استكشف المخرجات ثم اختر المزيج المناسب لأعمالك.",deliverables:"ما يتضمنه النظام",investment:"التكلفة المنشورة",discuss:"ناقش هذا النظام",pathTitle:["أعمالك هي المخطط.","نحن نربط الأجزاء."],pathIntro:"ابدأ بعائق واحد. ابنِ نظاماً مفيداً. وسّعه مع نمو أعمالك.",path:["أعمالك","تحديد العائق","تصميم النظام","ربط البيانات","أتمتة العمليات","إضافة الذكاء","التوسع"],cta:["ما الذي يمكن تحسينه؟","لنبدأ من هنا."],ctaIntro:"أحضر العملية أو الأداة المنفصلة أو الفكرة. سنوضح الخطوة التالية.",audit:"مراجعة مجانية لمدة {minutes} دقيقة. تشخيص مكتوب. بداية عملية.",aboutLink:"كيف نفكر ونعمل",pause:"إيقاف الحركة",resume:"استئناف الحركة",reduced:"حركة مخفّضة",
  },
  hi: {
    meta:"आपके व्यवसाय के लिए जुड़े सॉफ़्टवेयर, AI एजेंट, स्वचालन, ERP और औद्योगिक IoT।",hero:["अलग-अलग क्षमताएँ।","एक जुड़ा व्यवसाय।"],intro:"हम सॉफ़्टवेयर, कनेक्शन और इंटेलिजेंस बनाते हैं जो बिखरी प्रक्रियाओं को आपके व्यवसाय के अनुसार काम करने वाले सिस्टम में बदलते हैं।",explore:"पूरा सिस्टम जानें",heroNote:"पहले संकेत से अगली उपयोगी कार्रवाई तक।",story:["व्यावसायिक समस्या","जुड़ा सिस्टम","स्वचालन","इंटेलिजेंस","व्यावसायिक परिणाम"],chapters:["सेवाओं का तंत्र","AI और स्वचालन","औद्योगिक जुड़ाव","हमारे सेवा सिस्टम","आपके लिए बना","अगला कदम"],ecosystem:["रुकावट से शुरुआत करें।","सही क्षमताएँ जोड़ें।"],ecosystemIntro:"जानें कि हर क्षमता क्या बदलती है। असली मूल्य उनके साथ काम करने में है।",selectHint:"एक क्षमता चुनें",detailLabels:["समस्या","हम क्या बनाते हैं","यह कैसे चलता है","क्या बदलता है"],diagramLabel:"काम करता जुड़ा सिस्टम",
    capabilities:{
      ai:["AI और बुद्धिमान एजेंट","टीम बार-बार जानकारी खोजती, समझती और तैयार करती है।","अनुमत संदर्भ और टूल के साथ AI सहायक और एजेंट।","अनुरोध सही डेटा, अनुमत APIs और मानवीय समीक्षा से जुड़ता है।","रोज़मर्रा के काम में उपयोगी उत्तर और तैयार कार्रवाई।",["व्यावसायिक प्रश्न","संदर्भ और AI एजेंट","समीक्षित कार्रवाई"]],
      automation:["व्यवसाय और वर्कफ़्लो स्वचालन","फ़ॉलो-अप, अनुमोदन और हस्तांतरण याद दिलाने पर निर्भर हैं।","नियम आधारित वर्कफ़्लो, CRM स्वचालन और अनुमोदन प्रक्रियाएँ।","घटना एक तय क्रम शुरू करती है; अपवाद सही व्यक्ति तक पहुँचते हैं।","कम पीछा करना और स्पष्ट ज़िम्मेदारी के साथ आगे बढ़ता काम।",["व्यावसायिक घटना","नियम और वर्कफ़्लो","काम पूरा"]],
      erp:["ERP और व्यावसायिक सिस्टम","खरीद, स्टॉक और वित्त अलग-अलग जानकारी पर काम करते हैं।","OperateOS: ERP मॉड्यूल, डैशबोर्ड और ग्राहक-विक्रेता पोर्टल।","साझा रिकॉर्ड विभाग, अनुमतियाँ और अनुमोदन जोड़ते हैं।","ऑर्डर से डिलीवरी तक एक परिचालन तस्वीर।",["ऑर्डर और स्टॉक","OperateOS / ERP","जुड़ा संचालन"]],
      industrial:["औद्योगिक IoT","मशीन की घटनाएँ व्यवसाय के निर्णयों तक नहीं पहुँचतीं।","सेंसर इंटीग्रेशन, उपकरण कनेक्टिविटी और परिचालन निगरानी।","सिग्नल स्थानीय कनेक्शन से सॉफ़्टवेयर और वर्कफ़्लो तक जाते हैं।","फ़ैक्टरी की स्पष्ट स्थिति और सही कार्रवाई।",["मशीन का सिग्नल","IoT और डेटा","ऑपरेटर की कार्रवाई"]],
      software:["कस्टम सॉफ़्टवेयर","प्रक्रिया स्प्रेडशीट और तैयार टूल की सीमाओं से आगे बढ़ गई है।","आंतरिक ऐप, फ़ील्ड टूल और संचालन के अनुसार सॉफ़्टवेयर।","भूमिकाएँ, डेटा और नियम रखरखाव योग्य ऐप बनते हैं।","ऐसा टूल जो टीम के असली काम के अनुसार हो।",["आपकी प्रक्रिया","कस्टम सॉफ़्टवेयर","आसान दैनिक काम"]],
      integrations:["APIs और सिस्टम इंटीग्रेशन","लोग अलग-अलग ऐप के बीच जानकारी कॉपी करते हैं।","मौजूदा सिस्टम के बीच API कनेक्शन और डेटा आदान-प्रदान।","जानकारी मिलाएँ, जाँचें और अपवाद संभालते हुए आगे भेजें।","कम दोहराव और हर टूल में एक जैसी जानकारी।",["मौजूदा टूल","APIs और इंटीग्रेशन","साझा संदर्भ"]],
      data:["डेटा और एनालिटिक्स","रिपोर्ट देर से आती हैं और तस्वीर अधूरी होती है।","जुड़े डेटासेट, परिचालन डैशबोर्ड और प्रबंधन रिपोर्ट।","स्रोत जोड़ें, माप तय करें और ज़रूरी संकेत दिखाएँ।","प्रदर्शन और अगले निर्णय की बेहतर समझ।",["बिखरा डेटा","एनालिटिक्स और डैशबोर्ड","जानकारी पर निर्णय"]],
      platforms:["कस्टम डिजिटल प्लेटफ़ॉर्म","अलग टूल के बीच ग्राहक और टीम का अनुभव टूटता है।","वेब प्लेटफ़ॉर्म, सेल्फ-सर्विस पोर्टल और जुड़े अनुभव।","उपयोगकर्ता अनुभव को CRM, ERP और वर्कफ़्लो से जोड़ें।","सहज यात्रा और पीछे जुड़ा संचालन।",["ग्राहक की ज़रूरत","प्लेटफ़ॉर्म और सिस्टम","जुड़ा अनुभव"]],
    },
    aiTitle:["संदर्भ के साथ इंटेलिजेंस।","नियंत्रण के साथ स्वचालन।"],aiIntro:"मॉडल को सही जानकारी, तय टूल और सुझाव से कार्रवाई तक स्पष्ट रास्ता चाहिए।",aiLabels:["व्यावसायिक अनुरोध","AI एजेंट","अनुमत टूल","मानवीय समीक्षा","व्यावसायिक कार्रवाई"],aiNotes:["एक प्रश्न या काम","संदर्भ समझता है","MCP + APIs","ज़रूरी अनुमोदन","दर्ज किया परिणाम"],modelNote:"OpenAI · Claude · Grok / xAI — काम के अनुसार चुनाव",aiFoot:"ERP, IoT और एनालिटिक्स संदर्भ देते हैं। वर्कफ़्लो कार्रवाई आगे बढ़ाते हैं। आपकी अनुमतियाँ सीमा तय करती हैं।",industrialTitle:["फ़ैक्टरी से","अगले निर्णय तक।"],industrialIntro:"भौतिक संचालन को व्यवसाय के सॉफ़्टवेयर से जोड़ें। सिग्नल तभी उपयोगी है जब उस पर कार्रवाई हो सके।",industrialSteps:["मशीनें","सेंसर","डेटा","सिस्टम","स्वचालन","इंटेलिजेंस","कार्रवाई"],industrialNotes:[{title:"घटना दर्ज करें",body:"उपकरण की स्थिति और उत्पादन संकेत एक साझा दृश्य में लाएँ।"},{title:"संदर्भ जोड़ें",body:"घटना को वर्क ऑर्डर, स्टॉक या रखरखाव से जोड़ें।"},{title:"जवाब संभव करें",body:"ऑपरेटर को बताएँ, काम तैयार करें और कार्रवाई दर्ज करें।"}],industrialFoot:"उदाहरणात्मक संरचना। कनेक्शन आपके उपकरण, प्रोटोकॉल और ढाँचे पर निर्भर हैं।",catalogTitle:["क्षमताएँ जुड़ती हैं।","दायरा स्पष्ट रहता है।"],catalogIntro:"हमारे मौजूदा सेवा सिस्टम एक व्यावहारिक शुरुआत देते हैं। काम का दायरा जानें और सही संयोजन चुनें।",deliverables:"सिस्टम में शामिल",investment:"प्रकाशित निवेश",discuss:"इस सिस्टम पर बात करें",pathTitle:["आपका व्यवसाय ही नक्शा है।","हम हिस्से जोड़ते हैं।"],pathIntro:"एक रुकावट से शुरू करें। उपयोगी सिस्टम बनाएँ। व्यवसाय के साथ बढ़ाएँ।",path:["आपका व्यवसाय","रुकावट पहचानें","सिस्टम डिज़ाइन करें","डेटा जोड़ें","संचालन स्वचालित करें","इंटेलिजेंस जोड़ें","विस्तार करें"],cta:["क्या बेहतर हो सकता है?","वहीं से शुरू करें।"],ctaIntro:"अपनी प्रक्रिया, अलग पड़े टूल या विचार के साथ आएँ। हम अगला कदम स्पष्ट करेंगे।",audit:"{minutes} मिनट का निःशुल्क ऑडिट। लिखित निदान। व्यावहारिक शुरुआत।",aboutLink:"हम कैसे सोचते और काम करते हैं",pause:"गति रोकें",resume:"गति चालू करें",reduced:"कम गति",
  },
  gu: {
    meta:"તમારા વ્યવસાય માટે જોડાયેલ સૉફ્ટવેર, AI એજન્ટ, સ્વચાલન, ERP અને ઔદ્યોગિક IoT.",hero:["અલગ અલગ ક્ષમતાઓ.","એક જોડાયેલો વ્યવસાય."],intro:"અમે સૉફ્ટવેર, જોડાણ અને બુદ્ધિમત્તા બનાવીએ છીએ જે વિખરાયેલી પ્રક્રિયાઓને તમારા વ્યવસાય પ્રમાણે કામ કરતી સિસ્ટમમાં ફેરવે છે.",explore:"સમગ્ર તંત્ર જાણો",heroNote:"પ્રથમ સંકેતથી આગળની ઉપયોગી કાર્યવાહી સુધી.",story:["વ્યવસાયિક સમસ્યા","જોડાયેલી સિસ્ટમ","સ્વચાલન","બુદ્ધિમત્તા","વ્યવસાયિક પરિણામ"],chapters:["સેવાઓનું તંત્ર","AI અને સ્વચાલન","ઔદ્યોગિક જોડાણ","અમારી સેવા સિસ્ટમો","તમારા માટે રચાયેલ","આગળનું પગલું"],ecosystem:["અવરોધથી શરૂઆત કરો.","યોગ્ય ક્ષમતાઓ જોડો."],ecosystemIntro:"દરેક ક્ષમતા શું બદલે છે તે જાણો. સાચું મૂલ્ય તેમના સાથે કામ કરવામાં છે.",selectHint:"એક ક્ષમતા પસંદ કરો",detailLabels:["સમસ્યા","અમે શું બનાવીએ છીએ","તે કેવી રીતે ચાલે છે","શું બદલાય છે"],diagramLabel:"કાર્યરત જોડાયેલી સિસ્ટમ",
    capabilities:{
      ai:["AI અને બુદ્ધિશાળી એજન્ટ","ટીમ વારંવાર માહિતી શોધે, સમજે અને તૈયાર કરે છે.","મંજૂર સંદર્ભ અને સાધનો સાથે AI સહાયકો અને એજન્ટ.","વિનંતી યોગ્ય માહિતી, મંજૂર APIs અને માનવીય સમીક્ષા સાથે જોડાય છે.","રોજિંદા કામમાં ઉપયોગી જવાબ અને તૈયાર કાર્યવાહી.",["વ્યવસાયિક પ્રશ્ન","સંદર્ભ અને AI એજન્ટ","સમીક્ષિત કાર્યવાહી"]],
      automation:["વ્યવસાય અને વર્કફ્લો સ્વચાલન","ફોલોઅપ, મંજૂરી અને હસ્તાંતરણ યાદ કરાવવા પર આધારિત છે.","નિયમ આધારિત વર્કફ્લો, CRM સ્વચાલન અને મંજૂરી પ્રક્રિયા.","ઘટના નક્કી ક્રમ શરૂ કરે છે અને અપવાદ યોગ્ય વ્યક્તિ સુધી પહોંચે છે.","ઓછી પૂછપરછ અને સ્પષ્ટ જવાબદારી સાથે આગળ વધતું કામ.",["વ્યવસાયિક ઘટના","નિયમો અને વર્કફ્લો","કાર્ય પૂર્ણ"]],
      erp:["ERP અને વ્યવસાયિક સિસ્ટમો","ખરીદી, સ્ટૉક અને નાણાં અલગ માહિતીથી કામ કરે છે.","OperateOS: ERP મોડ્યૂલ, ડૅશબોર્ડ અને ગ્રાહક-વિક્રેતા પોર્ટલ.","સહિયારા રેકોર્ડ વિભાગો, પરવાનગીઓ અને મંજૂરીઓને જોડે છે.","ઑર્ડરથી ડિલિવરી સુધી એક સંચાલન દૃશ્ય.",["ઑર્ડર અને સ્ટૉક","OperateOS / ERP","જોડાયેલું સંચાલન"]],
      industrial:["ઔદ્યોગિક IoT","મશીનની ઘટનાઓ વ્યવસાયિક નિર્ણયો સુધી પહોંચતી નથી.","સેન્સર એકીકરણ, સાધનોનું જોડાણ અને સંચાલનની દેખરેખ.","સંકેતો સ્થાનિક જોડાણથી સૉફ્ટવેર અને વર્કફ્લો સુધી જાય છે.","ફેક્ટરીની સ્પષ્ટ સ્થિતિ અને ઉપયોગી કાર્યવાહી.",["મશીનનો સંકેત","IoT અને માહિતી","ઑપરેટરની કાર્યવાહી"]],
      software:["કસ્ટમ સૉફ્ટવેર","પ્રક્રિયા સ્પ્રેડશીટ અને તૈયાર સાધનોની મર્યાદાથી આગળ વધી છે.","આંતરિક ઍપ, ફિલ્ડ સાધનો અને કામગીરી મુજબ સૉફ્ટવેર.","ભૂમિકા, માહિતી અને નિયમો જાળવણીયોગ્ય ઍપ બને છે.","ટીમના વાસ્તવિક કામને અનુરૂપ સાધન.",["તમારી પ્રક્રિયા","કસ્ટમ સૉફ્ટવેર","સરળ રોજિંદું કામ"]],
      integrations:["APIs અને સિસ્ટમ એકીકરણ","લોકો અલગ ઍપ વચ્ચે માહિતી કૉપી કરે છે.","હાલની સિસ્ટમો વચ્ચે API જોડાણ અને માહિતી વિનિમય.","માહિતી મેળવો, ચકાસો અને અપવાદ સંભાળીને આગળ મોકલો.","ઓછું પુનરાવર્તન અને સુસંગત માહિતી.",["હાલનાં સાધનો","APIs અને એકીકરણ","સહિયારો સંદર્ભ"]],
      data:["માહિતી અને એનાલિટિક્સ","અહેવાલ મોડા આવે છે અને દૃશ્ય અધૂરું હોય છે.","જોડાયેલ ડેટા, સંચાલન ડૅશબોર્ડ અને સંચાલકીય અહેવાલ.","સ્રોત જોડો, માપ નક્કી કરો અને જરૂરી સંકેતો બતાવો.","કાર્યક્ષમતા અને આગળના નિર્ણયની વધુ સારી સમજ.",["વિખરાયેલી માહિતી","એનાલિટિક્સ અને ડૅશબોર્ડ","માહિતી આધારિત નિર્ણય"]],
      platforms:["કસ્ટમ ડિજિટલ પ્લેટફૉર્મ","અલગ સાધનો વચ્ચે ગ્રાહક અને ટીમનો અનુભવ તૂટે છે.","વેબ પ્લેટફૉર્મ, સ્વસેવા પોર્ટલ અને જોડાયેલા અનુભવો.","વપરાશકર્તાના અનુભવને CRM, ERP અને વર્કફ્લો સાથે જોડો.","સરળ મુસાફરી અને પાછળ જોડાયેલું સંચાલન.",["ગ્રાહકની જરૂરિયાત","પ્લેટફૉર્મ અને સિસ્ટમો","જોડાયેલો અનુભવ"]],
    },
    aiTitle:["સંદર્ભ સાથે બુદ્ધિમત્તા.","નિયંત્રણ સાથે સ્વચાલન."],aiIntro:"મોડેલને યોગ્ય માહિતી, નક્કી સાધનો અને સૂચનથી કાર્યવાહી સુધી સ્પષ્ટ માર્ગ જોઈએ.",aiLabels:["વ્યવસાયિક વિનંતી","AI એજન્ટ","મંજૂર સાધનો","માનવીય સમીક્ષા","વ્યવસાયિક કાર્યવાહી"],aiNotes:["એક પ્રશ્ન કે કાર્ય","સંદર્ભ સમજે છે","MCP + APIs","જરૂરી મંજૂરીઓ","નોંધાયેલ પરિણામ"],modelNote:"OpenAI · Claude · Grok / xAI — કાર્ય પ્રમાણે પસંદગી",aiFoot:"ERP, IoT અને એનાલિટિક્સ સંદર્ભ આપે છે. વર્કફ્લો કાર્યવાહી આગળ વધારે છે. તમારી પરવાનગીઓ મર્યાદા નક્કી કરે છે.",industrialTitle:["ફેક્ટરીથી","આગળના નિર્ણય સુધી."],industrialIntro:"ભૌતિક કામગીરીને વ્યવસાયના સૉફ્ટવેર સાથે જોડો. સંકેત ત્યારે ઉપયોગી છે જ્યારે તેના પર કાર્યવાહી થઈ શકે.",industrialSteps:["મશીનો","સેન્સર","માહિતી","સિસ્ટમો","સ્વચાલન","બુદ્ધિમત્તા","કાર્યવાહી"],industrialNotes:[{title:"ઘટના નોંધો",body:"સાધનોની સ્થિતિ અને ઉત્પાદન સંકેતો સહિયારા દૃશ્યમાં લાવો."},{title:"સંદર્ભ ઉમેરો",body:"ઘટનાને વર્ક ઑર્ડર, સ્ટૉક કે જાળવણી સાથે જોડો."},{title:"પ્રતિસાદ શક્ય બનાવો",body:"ઑપરેટરને જણાવો, કાર્ય તૈયાર કરો અને કાર્યવાહી નોંધો."}],industrialFoot:"ઉદાહરણરૂપ રચના. જોડાણ તમારા સાધનો, પ્રોટોકૉલ અને માળખા પર આધારિત છે.",catalogTitle:["ક્ષમતાઓ જોડાય છે.","કાર્યનો વ્યાપ સ્પષ્ટ રહે છે."],catalogIntro:"અમારી હાલની સેવા સિસ્ટમો વ્યવહારુ શરૂઆત આપે છે. સમાવિષ્ટ કામ જાણો અને યોગ્ય સંયોજન પસંદ કરો.",deliverables:"સિસ્ટમમાં સામેલ",investment:"પ્રકાશિત રોકાણ",discuss:"આ સિસ્ટમ વિશે વાત કરો",pathTitle:["તમારો વ્યવસાય જ નકશો છે.","અમે ભાગોને જોડીએ છીએ."],pathIntro:"એક અવરોધથી શરૂ કરો. ઉપયોગી સિસ્ટમ બનાવો. વ્યવસાય સાથે વિસ્તારો.",path:["તમારો વ્યવસાય","અવરોધ શોધો","સિસ્ટમ રચો","માહિતી જોડો","કામગીરી સ્વચાલિત કરો","બુદ્ધિમત્તા ઉમેરો","વિસ્તારો"],cta:["શું વધુ સારું થઈ શકે?","ત્યાંથી શરૂઆત કરીએ."],ctaIntro:"તમારી પ્રક્રિયા, અલગ પડેલું સાધન કે વિચાર લાવો. અમે આગળનું પગલું સ્પષ્ટ કરીશું.",audit:"{minutes} મિનિટનું નિઃશુલ્ક ઑડિટ. લેખિત નિદાન. વ્યવહારુ શરૂઆત.",aboutLink:"અમે કેવી રીતે વિચારીએ અને કામ કરીએ",pause:"ગતિ રોકો",resume:"ગતિ ચાલુ કરો",reduced:"ઓછી ગતિ",
  },
  zh: {
    meta:"围绕您的业务连接软件、AI 智能体、自动化、ERP 和工业物联网。",hero:["各有所长。","连接为一。"],intro:"我们构建软件、连接与智能，将分散的流程转变为适合您业务的完整系统。",explore:"探索服务生态",heroNote:"从第一个信号，到下一步有用的行动。",story:["业务问题","互联系统","自动化","智能","业务成果"],chapters:["服务生态","AI 与自动化","工业互联","我们的服务系统","围绕您的业务","下一步"],ecosystem:["从瓶颈出发。","连接合适的能力。"],ecosystemIntro:"了解每种能力带来的改变。真正的价值在于它们如何协同工作。",selectHint:"选择一种能力",detailLabels:["业务问题","我们构建什么","如何运作","带来什么改变"],diagramLabel:"互联系统的实际应用",
    capabilities:{
      ai:["AI 与智能体","团队反复查找、解读和准备相同的信息。","使用经授权业务背景与工具的 AI 助手和智能体。","请求连接相关数据、允许的 APIs 和人工审核。","日常工作中的实用回答与准备好的行动。",["业务问题","背景与 AI 智能体","经审核的行动"]],
      automation:["业务与工作流自动化","跟进、审批和交接依赖人工记忆。","基于规则的工作流、CRM 自动化和审批流程。","事件启动明确的步骤，将异常交给相应负责人。","减少追问，让工作明确地向前推进。",["业务事件","规则与工作流","任务完成"]],
      erp:["ERP 与业务系统","采购、库存和财务使用不同版本的信息。","OperateOS：ERP 模块、运营看板及客户或供应商门户。","共享记录连接部门、权限和审批流程。","从订单到交付的一致运营视图。",["订单与库存","OperateOS / ERP","互联运营"]],
      industrial:["工业物联网","机器事件与生产更新未能进入业务决策。","传感器集成、设备连接和运营监测。","信号通过边缘连接进入软件、规则和工作流。","看清生产现场，并采取行动。",["机器信号","IoT 与数据","操作员行动"]],
      software:["定制软件","流程已超出表格和标准工具的能力范围。","适合实际运营的内部应用、现场工具和软件。","将角色、数据和业务规则转化为可维护的应用。","真正贴合团队工作方式的工具。",["您的流程","定制软件","更简单的日常工作"]],
      integrations:["APIs 与系统集成","人员在无法互通的应用之间复制信息。","现有系统之间的 API 连接和数据交换。","映射、验证并传递信息，明确处理异常。","减少重复录入，保持信息一致。",["现有工具","APIs 与集成","共享背景"]],
      data:["数据与分析","报告延迟，决策只能看到局部情况。","互联数据集、运营看板和管理报告。","汇集来源，定义指标，呈现关键的业务信号。","更清楚地了解表现与下一步决策。",["分散数据","分析与看板","有依据的决策"]],
      platforms:["定制数字平台","客户与团队的体验在独立工具之间中断。","网站平台、自助门户和互联数字体验。","将用户体验与 CRM、ERP、内容和工作流连接。","更顺畅的体验，背后有完整运营支撑。",["客户需求","平台与业务系统","互联体验"]],
    },
    aiTitle:["有背景的智能。","有控制的自动化。"],aiIntro:"模型需要相关信息、明确工具，以及从建议到行动的清晰路径。",aiLabels:["业务请求","AI 智能体","授权工具","人工审核","业务行动"],aiNotes:["一个问题或任务","理解业务背景","MCP + APIs","必要的审批","有记录的结果"],modelNote:"OpenAI · Claude · Grok / xAI — 根据任务选择",aiFoot:"ERP、IoT 和分析提供背景，工作流推动行动，您的权限设定边界。",industrialTitle:["从生产现场","到下一次决策。"],industrialIntro:"将物理运营与业务软件相连。有人能够据此行动时，信号才产生价值。",industrialSteps:["机器","传感器","数据","系统","自动化","智能","行动"],industrialNotes:[{title:"捕捉事件",body:"在共享视图中呈现设备状态与生产信号。"},{title:"加入背景",body:"将事件与工单、库存记录或维护流程连接。"},{title:"推动响应",body:"通知操作员，准备任务，记录下一步行动。"}],industrialFoot:"示意架构。具体连接取决于您的设备、协议和基础设施。",catalogTitle:["能力彼此连接。","范围始终清晰。"],catalogIntro:"现有服务系统提供切实的起点。了解交付内容，再组合适合您业务的方案。",deliverables:"系统包含内容",investment:"已公布的投入范围",discuss:"讨论这个系统",pathTitle:["您的业务就是蓝图。","我们连接各个部分。"],pathIntro:"从一个瓶颈开始，构建有用的系统，再随业务成长扩展。",path:["您的业务","找出瓶颈","设计系统","连接数据","自动化运营","加入智能","扩展"],cta:["哪里可以做得更好？","就从那里开始。"],ctaIntro:"带来您的流程、独立工具或想法，我们将一起明确下一步。",audit:"免费 {minutes} 分钟诊断，书面分析，切实的起点。",aboutLink:"我们的理念与方法",pause:"暂停动画",resume:"继续动画",reduced:"减少动画",
  },
};

export function getServicesCopy(locale: Locale): ServicesCopy {
  if (locale === "en") return SERVICES_EN;
  const translated = translations[locale];
  return { ...translated, capabilities: SERVICES_EN.capabilities.map(({ id }) => {
    const [name,problem,build,how,outcome,flow] = translated.capabilities[id];
    return { id,name,problem,build,how,outcome,flow };
  }) };
}
