/**
 * Pricing page — UI copy that is new with the home-style redesign.
 *
 * Everything that already existed stays in the locale dictionaries
 * (`getTranslation(locale).pricing`, `.faq`, `.cta`); only strings the old page
 * hard-coded, or that the new layout introduces, live here. English is the
 * source of truth; every other locale falls back to it key by key.
 *
 * NOTE: as of this redesign only `en.json` carries a `pricing` block, so the
 * tier content itself (names, prices, feature labels) renders in English for
 * every locale via the deep-merge fallback in lib/i18n. The strings below are
 * translated so the frame around that content reads natively.
 */

import type { Locale } from "@/lib/i18n";

export type CompareRowKey =
  | "uptime" | "storage" | "backups" | "email" | "cdn" | "support"
  | "research" | "technical" | "meta" | "local" | "content" | "cro" | "links" | "consulting" | "reporting";

export interface PickerOption { label: string; /** 0–3 = tier index, null = no preference */ tier: number | null }
export interface PickerQuestion { q: string; options: PickerOption[] }
export interface QuoteStep { label: string; title: string; body: string }

export interface PricingCopy {
  home: string;
  edition: string;
  heroLead: string;
  heroAccent: string;
  download: string;
  heroNote: string;
  figureTitle: string;
  figureAlt: string;
  figureCaption: [string, string];
  figureBlocks: [string, string, string];
  figureEnterprise: string;
  legend: [string, string, string];
  bandLabel: [string, string];
  facts: [string, string, string, string];
  chapters: [string, string, string, string, string, string];
  plansTitle: [string, string];
  plansIntro: string;
  included: string;
  extras: string;
  scope: string;
  compareTitle: [string, string];
  compareIntro: string;
  compareLabel: string;
  othersPrefix: string;
  rowLabels: Record<CompareRowKey, string>;
  yes: string;
  no: string;
  everythingIn: (tier: string) => string;
  pickerTitle: [string, string];
  pickerIntro: string;
  questions: PickerQuestion[];
  suggestion: string;
  startingPoint: string;
  defaultReason: string;
  reasons: [string, string, string, string];
  seePlan: (tier: string) => string;
  answered: (n: number, total: number) => string;
  reset: string;
  quoteTitle: [string, string];
  quoteIntro: string;
  steps: [QuoteStep, QuoteStep, QuoteStep, QuoteStep, QuoteStep, QuoteStep];
  railTitle: string;
  railAlt: string;
  bestValue: string;
  advantagesTitle: [string, string];
  advantagesIntro: string;
  systemEyebrow: string;
  systemTitle: [string, string];
  systemIntro: (siteDisplay: string, siteTier: string, systemDisplay: string, systemService: string) => string;
  systemFigureTitle: string;
  systemFigureAlt: string;
  systemsLabel: string;
  step1Label: string;
  step1Body: string;
  step2Label: (price: string) => string;
  step2Body: string;
  systemLink: string;
  faqTitle: [string, string];
  faqBody: string;
  faqLink: string;
  circuitLabel: string;
  footerCenter: string;
  backToTop: string;
  motion: { pause: string; paused: string; reduced: string; pauseAria: string; resumeAria: string; reducedAria: string };
}

const EN: PricingCopy = {
  home: "Home",
  edition: "Savin Group / Pricing",
  heroLead: "More system.",
  heroAccent: "Same budget.",
  download: "Download the price sheet (PDF)",
  heroNote: "Ranges in INR · the final quote follows the free audit",
  figureTitle: "Three tiers, one system",
  figureAlt: "Diagram: three ascending platforms labelled Launch, Growth and Scale on an isometric grid. Each carries more system blocks than the last — a site, then automation, then commerce and CRM — with signal paths rising from one platform to the next. A dashed fourth outline marks Enterprise, scoped separately.",
  figureCaption: ["THREE TIERS / ONE SYSTEM", "ILLUSTRATIVE SCOPE"],
  figureBlocks: ["SITE", "AUTOMATION", "COMMERCE / CRM"],
  figureEnterprise: "ENTERPRISE / CUSTOM SCOPE",
  legend: ["Tier platform", "Signal path", "System block"],
  bandLabel: ["How we price", "In one line."],
  facts: ["Requirement-based", "Free audit first", "No hidden costs", "INR starting ranges"],
  chapters: ["The plans", "Which plan fits?", "What a quote includes", "Why teams pick us", "The system behind each tier", "Before you sign"],
  plansTitle: ["Four scopes of work.", "One way of pricing."],
  plansIntro: "Every plan is a starting range, not a package. Pages, integrations and timelines are scoped after the free audit — the price moves with the requirement, never with a surprise.",
  included: "Included in the range",
  extras: "Free extras",
  scope: "Scope",
  compareTitle: ["Everything in every plan,", "side by side."],
  compareIntro: "The full feature list, one row per capability. Where other agencies bill an item separately, the row says so.",
  compareLabel: "Compare plans",
  othersPrefix: "Others",
  rowLabels: {
    uptime: "Uptime",
    storage: "Storage",
    backups: "Backups",
    email: "Email accounts",
    cdn: "CDN & edge protection",
    support: "Priority support",
    research: "Keyword & market research",
    technical: "On-page & technical SEO",
    meta: "Meta + schema setup",
    local: "Local SEO & Maps",
    content: "Content programme",
    cro: "Conversion-rate optimisation",
    links: "Link building",
    consulting: "Ongoing SEO consulting",
    reporting: "Revenue reporting",
  },
  yes: "Included",
  no: "Not included",
  everythingIn: (tier) => `Everything in ${tier}`,
  pickerTitle: ["Four questions.", "One honest starting point."],
  pickerIntro: "Answer what you know today. The suggestion is a place to start the conversation — the audit decides the final scope.",
  questions: [
    { q: "How many pages do you need?", options: [{ label: "Up to 12", tier: 0 }, { label: "12 – 30", tier: 1 }, { label: "30 – 60", tier: 2 }, { label: "A portal or platform", tier: 3 }] },
    { q: "Do you sell online?", options: [{ label: "Not yet", tier: null }, { label: "Leads & enquiries", tier: 1 }, { label: "Yes, a store", tier: 2 }] },
    { q: "How many locations?", options: [{ label: "One", tier: null }, { label: "2 – 5", tier: 2 }, { label: "Many, or multi-market", tier: 3 }] },
    { q: "Do you need ongoing SEO?", options: [{ label: "Not yet", tier: null }, { label: "Some", tier: 1 }, { label: "A full programme", tier: 2 }] },
  ],
  suggestion: "Our suggestion",
  startingPoint: "A starting point, not a quote",
  defaultReason: "Most teams start here: a conversion-tuned site with lead capture, SEO and analytics wired in.",
  reasons: [
    "A scoped, conversion-tuned site with foundational SEO — add automation later without a rebuild.",
    "The site plus WhatsApp lead capture, standard SEO and analytics — the shape most growing businesses need.",
    "Multi-location or e-commerce scope with automation, CRM wiring and an advanced SEO programme.",
    "Portals, ERP and multi-market builds are scoped from a paid discovery sprint, credited against the build.",
  ],
  seePlan: (tier) => `See the ${tier} plan`,
  answered: (n, total) => `${n} of ${total} answered`,
  reset: "Start over",
  quoteTitle: ["From first call", "to first year."],
  quoteIntro: "The engagement path is the same for every plan. Nothing is billed before the quote is fixed, and nothing is added to it afterwards.",
  steps: [
    { label: "Step 01 · Free", title: "Revenue audit", body: "A free 45-minute working session. You leave with a written diagnosis whether or not you hire us." },
    { label: "Step 02", title: "Scoped proposal", body: "Pages, integrations and timeline, written down. Enterprise scopes go through a paid discovery sprint first." },
    { label: "Step 03", title: "Fixed quote", body: "One number inside the plan’s range. No hourly meter, no add-ons discovered halfway through." },
    { label: "Step 04", title: "Build, with weekly demos", body: "You see working software every week and sign off each stage before the next one starts." },
    { label: "Step 05", title: "Launch", body: "DNS, SSL, analytics and search setup done by us — the site goes live measured, not just published." },
    { label: "Step 06 · Year 1", title: "Hosting & support", body: "First-year hosting, backups and human support are inside the quote. The engineer who built it answers." },
  ],
  railTitle: "The engagement path",
  railAlt: "Diagram: six connected stages on one rail — free audit, scoped proposal, fixed quote, build with weekly demos, launch, and first-year hosting and support.",
  bestValue: "Best value",
  advantagesTitle: ["Same budget.", "More of it working for you."],
  advantagesIntro: "The line items other agencies add after the quote are the line items we build in before it.",
  systemEyebrow: "How the two price lists fit together",
  systemTitle: ["Which tier gets you", "which system."],
  systemIntro: (site, tier, system, service) => `A tier is a scope of work. A system is what that scope delivers. The cheapest build is ${site} (${tier}); the cheapest complete system is ${system} (${service}) — the difference is the automation, SEO and analytics layered on top.`,
  systemFigureTitle: "Systems stack up with the tier",
  systemFigureAlt: "Diagram: four stacks, one per tier. Launch carries a single website layer; Growth the RevSite Pro system; Scale adds AutoSell Engine and LocalDom SEO; Enterprise is drawn as OperateOS and GlobalScale Suite in dashed outline, scoped separately.",
  systemsLabel: "Systems included",
  step1Label: "Step 1 · free",
  step1Body: "No cost and no commitment. You leave with a written diagnosis whether or not you hire us.",
  step2Label: (price) => `Step 2 · ${price}`,
  step2Body: "Only if you want a build scoped.",
  systemLink: "See what each system includes",
  faqTitle: ["Good questions.", "Straight answers."],
  faqBody: "Direct answers — no fluff. If you don’t see your question, ask it on the audit; we answer everything specific to your business, no slide deck, no pitch.",
  faqLink: "Still have questions? Ask on the audit",
  circuitLabel: "Your next chapter",
  footerCenter: "Requirement-based. Nothing hidden.",
  backToTop: "Back to top",
  motion: {
    pause: "Pause motion",
    paused: "Motion paused",
    reduced: "Reduced motion",
    pauseAria: "Pause diagram motion",
    resumeAria: "Resume diagram motion",
    reducedAria: "Motion reduced by your device preference",
  },
};

const ES: PricingCopy = {
  ...EN,
  home: "Inicio",
  edition: "Savin Group / Precios",
  heroLead: "Más sistema.",
  heroAccent: "Mismo presupuesto.",
  download: "Descargar la lista de precios (PDF)",
  heroNote: "Rangos en INR · el presupuesto final llega tras la auditoría gratuita",
  figureTitle: "Tres niveles, un sistema",
  figureAlt: "Diagrama: tres plataformas ascendentes —Launch, Growth y Scale— sobre una cuadrícula isométrica. Cada una lleva más bloques de sistema que la anterior: sitio, automatización, comercio y CRM, con señales que suben de una plataforma a la siguiente. Un cuarto contorno discontinuo marca Enterprise.",
  figureCaption: ["TRES NIVELES / UN SISTEMA", "ALCANCE ILUSTRATIVO"],
  figureBlocks: ["SITIO", "AUTOMATIZACIÓN", "COMERCIO / CRM"],
  figureEnterprise: "ENTERPRISE / ALCANCE A MEDIDA",
  legend: ["Plataforma del nivel", "Señal", "Bloque de sistema"],
  bandLabel: ["Cómo ponemos precio", "En una línea."],
  facts: ["Según requisitos", "Auditoría gratuita primero", "Sin costes ocultos", "Rangos iniciales en INR"],
  chapters: ["Los planes", "¿Qué plan encaja?", "Qué incluye un presupuesto", "Por qué nos eligen", "El sistema detrás de cada nivel", "Antes de firmar"],
  plansTitle: ["Cuatro alcances de trabajo.", "Una sola forma de fijar precio."],
  plansIntro: "Cada plan es un rango inicial, no un paquete. Páginas, integraciones y plazos se definen tras la auditoría gratuita: el precio se mueve con el requisito, nunca con una sorpresa.",
  included: "Incluido en el rango",
  extras: "Extras gratuitos",
  scope: "Alcance",
  compareTitle: ["Todo lo de cada plan,", "lado a lado."],
  compareIntro: "La lista completa de funciones, una fila por capacidad. Donde otras agencias facturan algo aparte, la fila lo indica.",
  compareLabel: "Comparar planes",
  othersPrefix: "Otros",
  rowLabels: { uptime: "Disponibilidad", storage: "Almacenamiento", backups: "Copias de seguridad", email: "Cuentas de correo", cdn: "CDN y protección", support: "Soporte prioritario", research: "Investigación de palabras clave y mercado", technical: "SEO on-page y técnico", meta: "Meta + schema", local: "SEO local y Maps", content: "Programa de contenidos", cro: "Optimización de conversión", links: "Link building", consulting: "Consultoría SEO continua", reporting: "Informes de ingresos" },
  yes: "Incluido",
  no: "No incluido",
  everythingIn: (tier) => `Todo lo de ${tier}`,
  pickerTitle: ["Cuatro preguntas.", "Un punto de partida honesto."],
  pickerIntro: "Responde lo que sepas hoy. La sugerencia es un punto de partida para la conversación; la auditoría decide el alcance final.",
  questions: [
    { q: "¿Cuántas páginas necesitas?", options: [{ label: "Hasta 12", tier: 0 }, { label: "12 – 30", tier: 1 }, { label: "30 – 60", tier: 2 }, { label: "Un portal o plataforma", tier: 3 }] },
    { q: "¿Vendes en línea?", options: [{ label: "Todavía no", tier: null }, { label: "Leads y consultas", tier: 1 }, { label: "Sí, una tienda", tier: 2 }] },
    { q: "¿Cuántas ubicaciones?", options: [{ label: "Una", tier: null }, { label: "2 – 5", tier: 2 }, { label: "Muchas o varios mercados", tier: 3 }] },
    { q: "¿Necesitas SEO continuo?", options: [{ label: "Todavía no", tier: null }, { label: "Algo", tier: 1 }, { label: "Un programa completo", tier: 2 }] },
  ],
  suggestion: "Nuestra sugerencia",
  startingPoint: "Un punto de partida, no un presupuesto",
  defaultReason: "La mayoría empieza aquí: un sitio orientado a conversión con captación de leads, SEO y analítica integrados.",
  reasons: [
    "Un sitio acotado y orientado a conversión con SEO básico; añade automatización después sin rehacerlo.",
    "El sitio más captación por WhatsApp, SEO estándar y analítica: la forma que necesitan la mayoría de negocios en crecimiento.",
    "Alcance multi-sede o e-commerce con automatización, CRM y un programa SEO avanzado.",
    "Portales, ERP y builds multi-mercado se definen en un sprint de discovery de pago, descontado del proyecto.",
  ],
  seePlan: (tier) => `Ver el plan ${tier}`,
  answered: (n, total) => `${n} de ${total} respondidas`,
  reset: "Empezar de nuevo",
  quoteTitle: ["De la primera llamada", "al primer año."],
  quoteIntro: "El recorrido es el mismo para todos los planes. Nada se factura antes de fijar el presupuesto y nada se añade después.",
  steps: [
    { label: "Paso 01 · Gratis", title: "Auditoría de ingresos", body: "Una sesión de trabajo gratuita de 45 minutos. Sales con un diagnóstico escrito, nos contrates o no." },
    { label: "Paso 02", title: "Propuesta acotada", body: "Páginas, integraciones y plazo, por escrito. Los alcances Enterprise pasan antes por un sprint de discovery de pago." },
    { label: "Paso 03", title: "Presupuesto fijo", body: "Una cifra dentro del rango del plan. Sin contador por horas ni extras descubiertos a mitad de camino." },
    { label: "Paso 04", title: "Build con demos semanales", body: "Ves software funcionando cada semana y apruebas cada etapa antes de la siguiente." },
    { label: "Paso 05", title: "Lanzamiento", body: "DNS, SSL, analítica y buscadores configurados por nosotros: el sitio sale medido, no solo publicado." },
    { label: "Paso 06 · Año 1", title: "Hosting y soporte", body: "El hosting del primer año, las copias y el soporte humano van dentro del presupuesto. Responde el ingeniero que lo construyó." },
  ],
  railTitle: "El recorrido del proyecto",
  railAlt: "Diagrama: seis etapas conectadas en un mismo raíl: auditoría gratuita, propuesta acotada, presupuesto fijo, build con demos semanales, lanzamiento y hosting y soporte del primer año.",
  bestValue: "Mejor valor",
  advantagesTitle: ["Mismo presupuesto.", "Más de él trabajando para ti."],
  advantagesIntro: "Las partidas que otras agencias añaden después del presupuesto son las que nosotros incluimos antes.",
  systemEyebrow: "Cómo encajan las dos listas de precios",
  systemTitle: ["Qué nivel te da", "qué sistema."],
  systemIntro: (site, tier, system, service) => `Un nivel es un alcance de trabajo. Un sistema es lo que ese alcance entrega. El build más económico es ${site} (${tier}); el sistema completo más económico es ${system} (${service}): la diferencia es la automatización, el SEO y la analítica que van encima.`,
  systemFigureTitle: "Los sistemas se apilan con el nivel",
  systemFigureAlt: "Diagrama: cuatro pilas, una por nivel. Launch lleva una sola capa de sitio web; Growth el sistema RevSite Pro; Scale añade AutoSell Engine y LocalDom SEO; Enterprise aparece como OperateOS y GlobalScale Suite en contorno discontinuo.",
  systemsLabel: "Sistemas incluidos",
  step1Label: "Paso 1 · gratis",
  step1Body: "Sin coste ni compromiso. Sales con un diagnóstico escrito, nos contrates o no.",
  step2Label: (price) => `Paso 2 · ${price}`,
  step2Body: "Solo si quieres acotar un build.",
  systemLink: "Ver qué incluye cada sistema",
  faqTitle: ["Buenas preguntas.", "Respuestas directas."],
  faqBody: "Respuestas directas, sin relleno. Si no ves tu pregunta, hazla en la auditoría: respondemos todo lo específico de tu negocio, sin presentación ni discurso.",
  faqLink: "¿Más preguntas? Hazlas en la auditoría",
  circuitLabel: "Tu próximo capítulo",
  footerCenter: "Según requisitos. Nada oculto.",
  backToTop: "Volver arriba",
  motion: { pause: "Pausar animación", paused: "Animación en pausa", reduced: "Animación reducida", pauseAria: "Pausar la animación de los diagramas", resumeAria: "Reanudar la animación de los diagramas", reducedAria: "Animación reducida por la preferencia de tu dispositivo" },
};

const FR: PricingCopy = {
  ...EN,
  home: "Accueil",
  edition: "Savin Group / Tarifs",
  heroLead: "Plus de système.",
  heroAccent: "Même budget.",
  download: "Télécharger la grille tarifaire (PDF)",
  heroNote: "Fourchettes en INR · le devis final suit l’audit gratuit",
  figureTitle: "Trois niveaux, un système",
  figureAlt: "Schéma : trois plateformes ascendantes — Launch, Growth et Scale — sur une grille isométrique. Chacune porte plus de blocs que la précédente : site, automatisation, commerce et CRM, avec des signaux qui montent d’une plateforme à l’autre. Un quatrième contour en pointillé marque Enterprise.",
  figureCaption: ["TROIS NIVEAUX / UN SYSTÈME", "PÉRIMÈTRE ILLUSTRATIF"],
  figureBlocks: ["SITE", "AUTOMATISATION", "COMMERCE / CRM"],
  figureEnterprise: "ENTERPRISE / PÉRIMÈTRE SUR MESURE",
  legend: ["Plateforme du niveau", "Signal", "Bloc système"],
  bandLabel: ["Notre façon de tarifer", "En une ligne."],
  facts: ["Selon le besoin", "Audit gratuit d’abord", "Aucun coût caché", "Fourchettes de départ en INR"],
  chapters: ["Les offres", "Quelle offre vous convient ?", "Ce que comprend un devis", "Pourquoi on nous choisit", "Le système derrière chaque niveau", "Avant de signer"],
  plansTitle: ["Quatre périmètres.", "Une seule façon de tarifer."],
  plansIntro: "Chaque offre est une fourchette de départ, pas un forfait. Pages, intégrations et délais sont cadrés après l’audit gratuit : le prix suit le besoin, jamais une surprise.",
  included: "Compris dans la fourchette",
  extras: "Extras offerts",
  scope: "Périmètre",
  compareTitle: ["Tout ce que contient chaque offre,", "côte à côte."],
  compareIntro: "La liste complète des fonctionnalités, une ligne par capacité. Quand d’autres agences facturent un poste à part, la ligne le dit.",
  compareLabel: "Comparer les offres",
  othersPrefix: "Ailleurs",
  rowLabels: { uptime: "Disponibilité", storage: "Stockage", backups: "Sauvegardes", email: "Comptes e-mail", cdn: "CDN et protection", support: "Support prioritaire", research: "Recherche mots-clés et marché", technical: "SEO on-page et technique", meta: "Meta + schema", local: "SEO local et Maps", content: "Programme de contenu", cro: "Optimisation de la conversion", links: "Netlinking", consulting: "Conseil SEO continu", reporting: "Reporting des revenus" },
  yes: "Inclus",
  no: "Non inclus",
  everythingIn: (tier) => `Tout ce que contient ${tier}`,
  pickerTitle: ["Quatre questions.", "Un point de départ honnête."],
  pickerIntro: "Répondez avec ce que vous savez aujourd’hui. La suggestion ouvre la conversation ; l’audit décide du périmètre final.",
  questions: [
    { q: "Combien de pages vous faut-il ?", options: [{ label: "Jusqu’à 12", tier: 0 }, { label: "12 – 30", tier: 1 }, { label: "30 – 60", tier: 2 }, { label: "Un portail ou une plateforme", tier: 3 }] },
    { q: "Vendez-vous en ligne ?", options: [{ label: "Pas encore", tier: null }, { label: "Leads et demandes", tier: 1 }, { label: "Oui, une boutique", tier: 2 }] },
    { q: "Combien de sites / agences ?", options: [{ label: "Un", tier: null }, { label: "2 – 5", tier: 2 }, { label: "Beaucoup, ou plusieurs marchés", tier: 3 }] },
    { q: "Besoin de SEO continu ?", options: [{ label: "Pas encore", tier: null }, { label: "Un peu", tier: 1 }, { label: "Un programme complet", tier: 2 }] },
  ],
  suggestion: "Notre suggestion",
  startingPoint: "Un point de départ, pas un devis",
  defaultReason: "La plupart des équipes commencent ici : un site pensé pour convertir, avec capture de leads, SEO et analytics intégrés.",
  reasons: [
    "Un site cadré et pensé pour convertir, avec un SEO de base ; l’automatisation s’ajoute plus tard sans refonte.",
    "Le site plus la capture de leads WhatsApp, un SEO standard et les analytics : la forme dont la plupart des entreprises en croissance ont besoin.",
    "Périmètre multi-sites ou e-commerce avec automatisation, câblage CRM et programme SEO avancé.",
    "Portails, ERP et projets multi-marchés sont cadrés dans un sprint de discovery payant, déduit du projet.",
  ],
  seePlan: (tier) => `Voir l’offre ${tier}`,
  answered: (n, total) => `${n} sur ${total} répondues`,
  reset: "Recommencer",
  quoteTitle: ["Du premier appel", "à la première année."],
  quoteIntro: "Le parcours est le même pour toutes les offres. Rien n’est facturé avant que le devis soit fixé, rien n’y est ajouté ensuite.",
  steps: [
    { label: "Étape 01 · Gratuit", title: "Audit de revenus", body: "Une session de travail gratuite de 45 minutes. Vous repartez avec un diagnostic écrit, que vous nous engagiez ou non." },
    { label: "Étape 02", title: "Proposition cadrée", body: "Pages, intégrations et calendrier, par écrit. Les périmètres Enterprise passent d’abord par un sprint de discovery payant." },
    { label: "Étape 03", title: "Devis fixe", body: "Un seul montant dans la fourchette de l’offre. Pas de compteur horaire, pas d’options découvertes à mi-parcours." },
    { label: "Étape 04", title: "Réalisation avec démos hebdomadaires", body: "Vous voyez du logiciel qui fonctionne chaque semaine et validez chaque étape avant la suivante." },
    { label: "Étape 05", title: "Mise en ligne", body: "DNS, SSL, analytics et configuration des moteurs de recherche faits par nous : le site part mesuré, pas seulement publié." },
    { label: "Étape 06 · Année 1", title: "Hébergement et support", body: "Hébergement, sauvegardes et support humain de la première année sont dans le devis. C’est l’ingénieur qui l’a construit qui répond." },
  ],
  railTitle: "Le parcours de la mission",
  railAlt: "Schéma : six étapes reliées sur un même rail — audit gratuit, proposition cadrée, devis fixe, réalisation avec démos hebdomadaires, mise en ligne, hébergement et support la première année.",
  bestValue: "Meilleur rapport",
  advantagesTitle: ["Même budget.", "Plus de budget qui travaille pour vous."],
  advantagesIntro: "Les postes que d’autres agences ajoutent après le devis sont ceux que nous intégrons avant.",
  systemEyebrow: "Comment les deux grilles tarifaires s’articulent",
  systemTitle: ["Quel niveau vous donne", "quel système."],
  systemIntro: (site, tier, system, service) => `Un niveau est un périmètre de travail. Un système est ce que ce périmètre livre. Le projet le moins cher est ${site} (${tier}) ; le système complet le moins cher est ${system} (${service}) — la différence, ce sont l’automatisation, le SEO et les analytics ajoutés par-dessus.`,
  systemFigureTitle: "Les systèmes s’empilent avec le niveau",
  systemFigureAlt: "Schéma : quatre piles, une par niveau. Launch porte une seule couche site web ; Growth le système RevSite Pro ; Scale ajoute AutoSell Engine et LocalDom SEO ; Enterprise apparaît en pointillé avec OperateOS et GlobalScale Suite.",
  systemsLabel: "Systèmes inclus",
  step1Label: "Étape 1 · gratuit",
  step1Body: "Sans frais ni engagement. Vous repartez avec un diagnostic écrit, que vous nous engagiez ou non.",
  step2Label: (price) => `Étape 2 · ${price}`,
  step2Body: "Seulement si vous voulez cadrer un projet.",
  systemLink: "Voir ce que comprend chaque système",
  faqTitle: ["Bonnes questions.", "Réponses directes."],
  faqBody: "Des réponses directes, sans remplissage. Si votre question n’y est pas, posez-la pendant l’audit : nous répondons à tout ce qui concerne votre entreprise, sans présentation ni discours.",
  faqLink: "D’autres questions ? Posez-les pendant l’audit",
  circuitLabel: "Votre prochain chapitre",
  footerCenter: "Selon le besoin. Rien de caché.",
  backToTop: "Haut de page",
  motion: { pause: "Mettre en pause", paused: "Animation en pause", reduced: "Animation réduite", pauseAria: "Mettre en pause l’animation des schémas", resumeAria: "Reprendre l’animation des schémas", reducedAria: "Animation réduite selon la préférence de votre appareil" },
};

const DE: PricingCopy = {
  ...EN,
  home: "Start",
  edition: "Savin Group / Preise",
  heroLead: "Mehr System.",
  heroAccent: "Gleiches Budget.",
  download: "Preisliste herunterladen (PDF)",
  heroNote: "Spannen in INR · das endgültige Angebot folgt auf das kostenlose Audit",
  figureTitle: "Drei Stufen, ein System",
  figureAlt: "Diagramm: drei aufsteigende Plattformen — Launch, Growth und Scale — auf einem isometrischen Raster. Jede trägt mehr Systembausteine als die vorherige: Website, Automatisierung, Commerce und CRM, mit Signalpfaden, die von Plattform zu Plattform aufsteigen. Ein gestrichelter vierter Umriss markiert Enterprise.",
  figureCaption: ["DREI STUFEN / EIN SYSTEM", "ILLUSTRATIVER UMFANG"],
  figureBlocks: ["WEBSITE", "AUTOMATISIERUNG", "COMMERCE / CRM"],
  figureEnterprise: "ENTERPRISE / INDIVIDUELLER UMFANG",
  legend: ["Stufen-Plattform", "Signalpfad", "Systembaustein"],
  bandLabel: ["So kalkulieren wir", "In einem Satz."],
  facts: ["Nach Anforderung", "Kostenloses Audit zuerst", "Keine versteckten Kosten", "Einstiegsspannen in INR"],
  chapters: ["Die Pakete", "Welches Paket passt?", "Was ein Angebot enthält", "Warum Teams uns wählen", "Das System hinter jeder Stufe", "Vor der Unterschrift"],
  plansTitle: ["Vier Leistungsumfänge.", "Eine Art zu kalkulieren."],
  plansIntro: "Jedes Paket ist eine Einstiegsspanne, kein Fixpaket. Seiten, Integrationen und Zeitplan werden nach dem kostenlosen Audit festgelegt – der Preis folgt der Anforderung, nie einer Überraschung.",
  included: "In der Spanne enthalten",
  extras: "Kostenlose Extras",
  scope: "Umfang",
  compareTitle: ["Alles aus jedem Paket,", "nebeneinander."],
  compareIntro: "Die vollständige Funktionsliste, eine Zeile pro Leistung. Wo andere Agenturen einen Posten separat berechnen, steht es in der Zeile.",
  compareLabel: "Pakete vergleichen",
  othersPrefix: "Andere",
  rowLabels: { uptime: "Verfügbarkeit", storage: "Speicher", backups: "Backups", email: "E-Mail-Konten", cdn: "CDN & Schutz", support: "Priorisierter Support", research: "Keyword- & Marktrecherche", technical: "On-Page & technisches SEO", meta: "Meta + Schema", local: "Lokales SEO & Maps", content: "Content-Programm", cro: "Conversion-Optimierung", links: "Linkaufbau", consulting: "Laufende SEO-Beratung", reporting: "Umsatz-Reporting" },
  yes: "Enthalten",
  no: "Nicht enthalten",
  everythingIn: (tier) => `Alles in ${tier}`,
  pickerTitle: ["Vier Fragen.", "Ein ehrlicher Ausgangspunkt."],
  pickerIntro: "Beantworten Sie, was Sie heute wissen. Der Vorschlag eröffnet das Gespräch – den endgültigen Umfang legt das Audit fest.",
  questions: [
    { q: "Wie viele Seiten brauchen Sie?", options: [{ label: "Bis 12", tier: 0 }, { label: "12 – 30", tier: 1 }, { label: "30 – 60", tier: 2 }, { label: "Ein Portal oder eine Plattform", tier: 3 }] },
    { q: "Verkaufen Sie online?", options: [{ label: "Noch nicht", tier: null }, { label: "Leads & Anfragen", tier: 1 }, { label: "Ja, ein Shop", tier: 2 }] },
    { q: "Wie viele Standorte?", options: [{ label: "Einer", tier: null }, { label: "2 – 5", tier: 2 }, { label: "Viele oder mehrere Märkte", tier: 3 }] },
    { q: "Brauchen Sie laufendes SEO?", options: [{ label: "Noch nicht", tier: null }, { label: "Etwas", tier: 1 }, { label: "Ein volles Programm", tier: 2 }] },
  ],
  suggestion: "Unser Vorschlag",
  startingPoint: "Ein Ausgangspunkt, kein Angebot",
  defaultReason: "Die meisten Teams starten hier: eine auf Conversion abgestimmte Website mit Lead-Erfassung, SEO und Analytics.",
  reasons: [
    "Eine klar umrissene, auf Conversion abgestimmte Website mit Basis-SEO – Automatisierung kommt später ohne Neubau dazu.",
    "Website plus WhatsApp-Lead-Erfassung, Standard-SEO und Analytics – die Form, die die meisten wachsenden Unternehmen brauchen.",
    "Mehrere Standorte oder E-Commerce mit Automatisierung, CRM-Anbindung und einem erweiterten SEO-Programm.",
    "Portale, ERP und Multi-Markt-Projekte werden in einem bezahlten Discovery-Sprint festgelegt, der mit dem Projekt verrechnet wird.",
  ],
  seePlan: (tier) => `Paket ${tier} ansehen`,
  answered: (n, total) => `${n} von ${total} beantwortet`,
  reset: "Von vorn beginnen",
  quoteTitle: ["Vom ersten Gespräch", "bis zum ersten Jahr."],
  quoteIntro: "Der Ablauf ist für jedes Paket derselbe. Vor dem festen Angebot wird nichts berechnet, danach nichts hinzugefügt.",
  steps: [
    { label: "Schritt 01 · Kostenlos", title: "Umsatz-Audit", body: "Eine kostenlose 45-minütige Arbeitssitzung. Sie gehen mit einer schriftlichen Diagnose – ob Sie uns beauftragen oder nicht." },
    { label: "Schritt 02", title: "Umrissenes Angebot", body: "Seiten, Integrationen und Zeitplan, schriftlich. Enterprise-Umfänge durchlaufen zuerst einen bezahlten Discovery-Sprint." },
    { label: "Schritt 03", title: "Festpreis", body: "Eine Zahl innerhalb der Spanne des Pakets. Kein Stundenzähler, keine Zusatzposten, die unterwegs auftauchen." },
    { label: "Schritt 04", title: "Umsetzung mit wöchentlichen Demos", body: "Sie sehen jede Woche funktionierende Software und nehmen jede Stufe ab, bevor die nächste beginnt." },
    { label: "Schritt 05", title: "Launch", body: "DNS, SSL, Analytics und Suchmaschinen-Setup übernehmen wir – die Website geht gemessen live, nicht nur veröffentlicht." },
    { label: "Schritt 06 · Jahr 1", title: "Hosting & Support", body: "Hosting, Backups und menschlicher Support im ersten Jahr sind im Angebot enthalten. Es antwortet der Ingenieur, der es gebaut hat." },
  ],
  railTitle: "Der Projektablauf",
  railAlt: "Diagramm: sechs verbundene Stufen auf einer Schiene – kostenloses Audit, umrissenes Angebot, Festpreis, Umsetzung mit wöchentlichen Demos, Launch sowie Hosting und Support im ersten Jahr.",
  bestValue: "Bestes Verhältnis",
  advantagesTitle: ["Gleiches Budget.", "Mehr davon arbeitet für Sie."],
  advantagesIntro: "Die Posten, die andere Agenturen nach dem Angebot hinzufügen, bauen wir davor ein.",
  systemEyebrow: "Wie die beiden Preislisten zusammenpassen",
  systemTitle: ["Welche Stufe bringt", "welches System."],
  systemIntro: (site, tier, system, service) => `Eine Stufe ist ein Leistungsumfang. Ein System ist das, was dieser Umfang liefert. Der günstigste Build ist ${site} (${tier}); das günstigste vollständige System ist ${system} (${service}) – der Unterschied sind Automatisierung, SEO und Analytics obendrauf.`,
  systemFigureTitle: "Systeme stapeln sich mit der Stufe",
  systemFigureAlt: "Diagramm: vier Stapel, einer pro Stufe. Launch trägt eine einzelne Website-Schicht; Growth das RevSite-Pro-System; Scale ergänzt AutoSell Engine und LocalDom SEO; Enterprise ist gestrichelt als OperateOS und GlobalScale Suite gezeichnet.",
  systemsLabel: "Enthaltene Systeme",
  step1Label: "Schritt 1 · kostenlos",
  step1Body: "Ohne Kosten und ohne Verpflichtung. Sie gehen mit einer schriftlichen Diagnose – ob Sie uns beauftragen oder nicht.",
  step2Label: (price) => `Schritt 2 · ${price}`,
  step2Body: "Nur, wenn Sie einen Build umreißen lassen möchten.",
  systemLink: "Was jedes System enthält",
  faqTitle: ["Gute Fragen.", "Klare Antworten."],
  faqBody: "Direkte Antworten ohne Füllstoff. Fehlt Ihre Frage, stellen Sie sie im Audit – wir beantworten alles, was Ihr Unternehmen betrifft, ohne Foliensatz und ohne Pitch.",
  faqLink: "Noch Fragen? Im Audit stellen",
  circuitLabel: "Ihr nächstes Kapitel",
  footerCenter: "Nach Anforderung. Nichts versteckt.",
  backToTop: "Nach oben",
  motion: { pause: "Animation pausieren", paused: "Animation pausiert", reduced: "Reduzierte Animation", pauseAria: "Diagramm-Animation pausieren", resumeAria: "Diagramm-Animation fortsetzen", reducedAria: "Animation gemäß Geräteeinstellung reduziert" },
};

const AR: PricingCopy = {
  ...EN,
  home: "الرئيسية",
  edition: "Savin Group / الأسعار",
  heroLead: "نظام أكبر.",
  heroAccent: "بالميزانية نفسها.",
  download: "تنزيل قائمة الأسعار (PDF)",
  heroNote: "النطاقات بالروبية الهندية · العرض النهائي بعد التدقيق المجاني",
  figureTitle: "ثلاث فئات، نظام واحد",
  figureAlt: "رسم توضيحي: ثلاث منصات متصاعدة — Launch وGrowth وScale — على شبكة متساوية القياس. تحمل كل منصة كتل نظام أكثر من سابقتها: الموقع، ثم الأتمتة، ثم التجارة وإدارة العملاء، مع مسارات إشارة تصعد من منصة إلى التالية. إطار رابع متقطع يمثل Enterprise.",
  figureCaption: ["ثلاث فئات / نظام واحد", "نطاق توضيحي"],
  figureBlocks: ["الموقع", "الأتمتة", "التجارة / CRM"],
  figureEnterprise: "ENTERPRISE / نطاق مخصص",
  legend: ["منصة الفئة", "مسار الإشارة", "كتلة نظام"],
  bandLabel: ["كيف نسعّر", "في سطر واحد."],
  facts: ["حسب المتطلبات", "تدقيق مجاني أولاً", "لا تكاليف خفية", "نطاقات بداية بالروبية الهندية"],
  chapters: ["الخطط", "أي خطة تناسبك؟", "ماذا يشمل العرض", "لماذا تختارنا الفرق", "النظام وراء كل فئة", "قبل التوقيع"],
  plansTitle: ["أربعة نطاقات عمل.", "طريقة واحدة للتسعير."],
  plansIntro: "كل خطة نطاق بداية لا باقة جاهزة. تُحدَّد الصفحات والتكاملات والجداول الزمنية بعد التدقيق المجاني — السعر يتحرك مع المتطلبات، لا مع المفاجآت.",
  included: "مشمول في النطاق",
  extras: "إضافات مجانية",
  scope: "النطاق",
  compareTitle: ["كل ما في كل خطة،", "جنباً إلى جنب."],
  compareIntro: "قائمة الميزات الكاملة، صف لكل قدرة. وحيث تفوتر وكالات أخرى بنداً على حدة، يذكر الصف ذلك.",
  compareLabel: "قارن الخطط",
  othersPrefix: "الآخرون",
  rowLabels: { uptime: "وقت التشغيل", storage: "التخزين", backups: "النسخ الاحتياطي", email: "حسابات البريد", cdn: "CDN والحماية", support: "دعم ذو أولوية", research: "بحث الكلمات المفتاحية والسوق", technical: "SEO داخلي وتقني", meta: "إعداد Meta + Schema", local: "SEO محلي وخرائط", content: "برنامج المحتوى", cro: "تحسين معدل التحويل", links: "بناء الروابط", consulting: "استشارات SEO مستمرة", reporting: "تقارير الإيرادات" },
  yes: "مشمول",
  no: "غير مشمول",
  everythingIn: (tier) => `كل ما في ${tier}`,
  pickerTitle: ["أربعة أسئلة.", "نقطة بداية صادقة."],
  pickerIntro: "أجب بما تعرفه اليوم. الاقتراح نقطة لبدء الحوار — والتدقيق يحدد النطاق النهائي.",
  questions: [
    { q: "كم صفحة تحتاج؟", options: [{ label: "حتى 12", tier: 0 }, { label: "12 – 30", tier: 1 }, { label: "30 – 60", tier: 2 }, { label: "بوابة أو منصة", tier: 3 }] },
    { q: "هل تبيع عبر الإنترنت؟", options: [{ label: "ليس بعد", tier: null }, { label: "عملاء محتملون واستفسارات", tier: 1 }, { label: "نعم، متجر", tier: 2 }] },
    { q: "كم عدد الفروع؟", options: [{ label: "فرع واحد", tier: null }, { label: "2 – 5", tier: 2 }, { label: "كثيرة أو أسواق متعددة", tier: 3 }] },
    { q: "هل تحتاج SEO مستمراً؟", options: [{ label: "ليس بعد", tier: null }, { label: "بعض الشيء", tier: 1 }, { label: "برنامج كامل", tier: 2 }] },
  ],
  suggestion: "اقتراحنا",
  startingPoint: "نقطة بداية، لا عرض سعر",
  defaultReason: "معظم الفرق تبدأ هنا: موقع مضبوط للتحويل مع التقاط العملاء المحتملين وSEO وتحليلات مدمجة.",
  reasons: [
    "موقع محدد النطاق ومضبوط للتحويل مع SEO أساسي — أضف الأتمتة لاحقاً دون إعادة بناء.",
    "الموقع مع التقاط العملاء عبر واتساب وSEO قياسي وتحليلات — الشكل الذي تحتاجه معظم الأعمال النامية.",
    "نطاق متعدد الفروع أو تجارة إلكترونية مع أتمتة وربط CRM وبرنامج SEO متقدم.",
    "البوابات وأنظمة ERP والمشاريع متعددة الأسواق تُحدَّد عبر سبرنت اكتشاف مدفوع يُخصم من قيمة المشروع.",
  ],
  seePlan: (tier) => `اطّلع على خطة ${tier}`,
  answered: (n, total) => `${n} من ${total} تمت الإجابة عنها`,
  reset: "ابدأ من جديد",
  quoteTitle: ["من أول مكالمة", "إلى أول سنة."],
  quoteIntro: "مسار العمل واحد لكل الخطط. لا تُفوتر أي مبالغ قبل تثبيت العرض، ولا يُضاف إليه شيء بعده.",
  steps: [
    { label: "الخطوة 01 · مجاناً", title: "تدقيق الإيرادات", body: "جلسة عمل مجانية مدتها 45 دقيقة. تخرج بتشخيص مكتوب سواء تعاقدت معنا أم لا." },
    { label: "الخطوة 02", title: "مقترح محدد النطاق", body: "الصفحات والتكاملات والجدول الزمني مكتوبة. نطاقات Enterprise تمر أولاً بسبرنت اكتشاف مدفوع." },
    { label: "الخطوة 03", title: "عرض سعر ثابت", body: "رقم واحد ضمن نطاق الخطة. لا عدّاد ساعات ولا إضافات تُكتشف في منتصف الطريق." },
    { label: "الخطوة 04", title: "البناء مع عروض أسبوعية", body: "ترى برمجيات تعمل كل أسبوع وتعتمد كل مرحلة قبل بدء التالية." },
    { label: "الخطوة 05", title: "الإطلاق", body: "نتولى DNS وSSL والتحليلات وإعداد محركات البحث — يُطلق الموقع مقاساً لا منشوراً فقط." },
    { label: "الخطوة 06 · السنة الأولى", title: "الاستضافة والدعم", body: "استضافة السنة الأولى والنسخ الاحتياطي والدعم البشري داخل العرض. ويجيبك المهندس الذي بناه." },
  ],
  railTitle: "مسار العمل",
  railAlt: "رسم توضيحي: ست مراحل متصلة على سكة واحدة — تدقيق مجاني، مقترح محدد النطاق، عرض سعر ثابت، بناء مع عروض أسبوعية، إطلاق، ثم استضافة ودعم في السنة الأولى.",
  bestValue: "أفضل قيمة",
  advantagesTitle: ["الميزانية نفسها.", "والمزيد منها يعمل لصالحك."],
  advantagesIntro: "البنود التي تضيفها وكالات أخرى بعد العرض هي البنود التي نبنيها قبله.",
  systemEyebrow: "كيف تتكامل قائمتا الأسعار",
  systemTitle: ["أي فئة تمنحك", "أي نظام."],
  systemIntro: (site, tier, system, service) => `الفئة نطاق عمل. والنظام هو ما يقدمه ذلك النطاق. أرخص بناء هو ${site} (${tier})؛ وأرخص نظام متكامل هو ${system} (${service}) — والفرق هو الأتمتة وSEO والتحليلات المضافة فوقه.`,
  systemFigureTitle: "الأنظمة تتراكم مع الفئة",
  systemFigureAlt: "رسم توضيحي: أربع رزم، واحدة لكل فئة. Launch تحمل طبقة موقع واحدة؛ Growth نظام RevSite Pro؛ Scale تضيف AutoSell Engine وLocalDom SEO؛ وEnterprise مرسومة بخط متقطع كـ OperateOS وGlobalScale Suite.",
  systemsLabel: "الأنظمة المشمولة",
  step1Label: "الخطوة 1 · مجاناً",
  step1Body: "بلا تكلفة ولا التزام. تخرج بتشخيص مكتوب سواء تعاقدت معنا أم لا.",
  step2Label: (price) => `الخطوة 2 · ${price}`,
  step2Body: "فقط إذا أردت تحديد نطاق بناء.",
  systemLink: "اطّلع على ما يشمله كل نظام",
  faqTitle: ["أسئلة جيدة.", "إجابات مباشرة."],
  faqBody: "إجابات مباشرة بلا حشو. إن لم تجد سؤالك، اطرحه أثناء التدقيق — نجيب عن كل ما يخص عملك، بلا عرض تقديمي ولا خطاب بيع.",
  faqLink: "لديك أسئلة أخرى؟ اطرحها في التدقيق",
  circuitLabel: "فصلك التالي",
  footerCenter: "حسب المتطلبات. لا شيء خفي.",
  backToTop: "العودة إلى الأعلى",
  motion: { pause: "إيقاف الحركة", paused: "الحركة متوقفة", reduced: "حركة مخفَّضة", pauseAria: "إيقاف حركة الرسوم", resumeAria: "استئناف حركة الرسوم", reducedAria: "الحركة مخفَّضة وفق إعدادات جهازك" },
};

const HI: PricingCopy = {
  ...EN,
  home: "होम",
  edition: "Savin Group / प्राइसिंग",
  heroLead: "ज़्यादा सिस्टम।",
  heroAccent: "वही बजट।",
  download: "प्राइस शीट डाउनलोड करें (PDF)",
  heroNote: "रेंज INR में · अंतिम कोटेशन मुफ़्त ऑडिट के बाद",
  figureTitle: "तीन टियर, एक सिस्टम",
  figureAlt: "आरेख: आइसोमेट्रिक ग्रिड पर तीन ऊपर उठते प्लेटफ़ॉर्म — Launch, Growth और Scale। हर एक पिछले से ज़्यादा सिस्टम ब्लॉक रखता है — साइट, फिर ऑटोमेशन, फिर कॉमर्स और CRM — और सिग्नल पथ एक प्लेटफ़ॉर्म से अगले तक ऊपर जाते हैं। चौथी डैश्ड रूपरेखा Enterprise को दर्शाती है।",
  figureCaption: ["तीन टियर / एक सिस्टम", "उदाहरणात्मक स्कोप"],
  figureBlocks: ["साइट", "ऑटोमेशन", "कॉमर्स / CRM"],
  figureEnterprise: "ENTERPRISE / कस्टम स्कोप",
  legend: ["टियर प्लेटफ़ॉर्म", "सिग्नल पथ", "सिस्टम ब्लॉक"],
  bandLabel: ["हम कीमत कैसे तय करते हैं", "एक पंक्ति में।"],
  facts: ["ज़रूरत के आधार पर", "पहले मुफ़्त ऑडिट", "कोई छिपी लागत नहीं", "INR में शुरुआती रेंज"],
  chapters: ["प्लान", "कौन-सा प्लान सही है?", "कोटेशन में क्या शामिल है", "टीमें हमें क्यों चुनती हैं", "हर टियर के पीछे का सिस्टम", "साइन करने से पहले"],
  plansTitle: ["चार तरह का काम।", "कीमत तय करने का एक तरीका।"],
  plansIntro: "हर प्लान एक शुरुआती रेंज है, पैकेज नहीं। पेज, इंटीग्रेशन और समय-सीमा मुफ़्त ऑडिट के बाद तय होते हैं — कीमत ज़रूरत के साथ बदलती है, कभी किसी सरप्राइज़ से नहीं।",
  included: "रेंज में शामिल",
  extras: "मुफ़्त एक्स्ट्रा",
  scope: "स्कोप",
  compareTitle: ["हर प्लान की हर चीज़,", "आमने-सामने।"],
  compareIntro: "पूरी फ़ीचर सूची, हर क्षमता के लिए एक पंक्ति। जहाँ दूसरी एजेंसियाँ अलग से बिल करती हैं, वह पंक्ति में लिखा है।",
  compareLabel: "प्लान तुलना",
  othersPrefix: "अन्य",
  rowLabels: { uptime: "अपटाइम", storage: "स्टोरेज", backups: "बैकअप", email: "ईमेल अकाउंट", cdn: "CDN और सुरक्षा", support: "प्राथमिकता सपोर्ट", research: "कीवर्ड और मार्केट रिसर्च", technical: "ऑन-पेज और तकनीकी SEO", meta: "Meta + Schema सेटअप", local: "लोकल SEO और Maps", content: "कंटेंट प्रोग्राम", cro: "कन्वर्ज़न-रेट ऑप्टिमाइज़ेशन", links: "लिंक बिल्डिंग", consulting: "निरंतर SEO परामर्श", reporting: "रेवेन्यू रिपोर्टिंग" },
  yes: "शामिल",
  no: "शामिल नहीं",
  everythingIn: (tier) => `${tier} में सब कुछ`,
  pickerTitle: ["चार सवाल।", "एक ईमानदार शुरुआत।"],
  pickerIntro: "आज जो पता है, वही बताइए। सुझाव बातचीत की शुरुआत है — अंतिम स्कोप ऑडिट तय करता है।",
  questions: [
    { q: "आपको कितने पेज चाहिए?", options: [{ label: "12 तक", tier: 0 }, { label: "12 – 30", tier: 1 }, { label: "30 – 60", tier: 2 }, { label: "पोर्टल या प्लेटफ़ॉर्म", tier: 3 }] },
    { q: "क्या आप ऑनलाइन बेचते हैं?", options: [{ label: "अभी नहीं", tier: null }, { label: "लीड और पूछताछ", tier: 1 }, { label: "हाँ, स्टोर", tier: 2 }] },
    { q: "कितनी लोकेशन?", options: [{ label: "एक", tier: null }, { label: "2 – 5", tier: 2 }, { label: "कई, या कई बाज़ार", tier: 3 }] },
    { q: "क्या निरंतर SEO चाहिए?", options: [{ label: "अभी नहीं", tier: null }, { label: "थोड़ा", tier: 1 }, { label: "पूरा प्रोग्राम", tier: 2 }] },
  ],
  suggestion: "हमारा सुझाव",
  startingPoint: "शुरुआती बिंदु, कोटेशन नहीं",
  defaultReason: "ज़्यादातर टीमें यहीं से शुरू करती हैं: लीड कैप्चर, SEO और एनालिटिक्स के साथ कन्वर्ज़न-ट्यून्ड साइट।",
  reasons: [
    "बुनियादी SEO के साथ स्कोप्ड, कन्वर्ज़न-ट्यून्ड साइट — ऑटोमेशन बाद में बिना रीबिल्ड जोड़ें।",
    "साइट के साथ WhatsApp लीड कैप्चर, स्टैंडर्ड SEO और एनालिटिक्स — बढ़ते व्यवसायों की आम ज़रूरत।",
    "ऑटोमेशन, CRM वायरिंग और एडवांस SEO प्रोग्राम के साथ मल्टी-लोकेशन या ई-कॉमर्स स्कोप।",
    "पोर्टल, ERP और मल्टी-मार्केट बिल्ड पेड डिस्कवरी स्प्रिंट से स्कोप होते हैं, जो बिल्ड में समायोजित होता है।",
  ],
  seePlan: (tier) => `${tier} प्लान देखें`,
  answered: (n, total) => `${total} में से ${n} के जवाब दिए`,
  reset: "फिर से शुरू करें",
  quoteTitle: ["पहली कॉल से", "पहले साल तक।"],
  quoteIntro: "हर प्लान के लिए रास्ता एक ही है। कोटेशन तय होने से पहले कुछ बिल नहीं होता, और बाद में कुछ जोड़ा नहीं जाता।",
  steps: [
    { label: "चरण 01 · मुफ़्त", title: "रेवेन्यू ऑडिट", body: "45 मिनट का मुफ़्त वर्किंग सेशन। आप लिखित डायग्नोसिस लेकर जाते हैं — चाहे हमें चुनें या नहीं।" },
    { label: "चरण 02", title: "स्कोप्ड प्रस्ताव", body: "पेज, इंटीग्रेशन और समय-सीमा, लिखित में। Enterprise स्कोप पहले पेड डिस्कवरी स्प्रिंट से गुज़रते हैं।" },
    { label: "चरण 03", title: "फ़िक्स्ड कोटेशन", body: "प्लान की रेंज के भीतर एक अंक। न घंटे का मीटर, न बीच में मिलने वाले ऐड-ऑन।" },
    { label: "चरण 04", title: "साप्ताहिक डेमो के साथ बिल्ड", body: "हर हफ़्ते चलता हुआ सॉफ़्टवेयर देखें और अगले चरण से पहले हर चरण को मंज़ूरी दें।" },
    { label: "चरण 05", title: "लॉन्च", body: "DNS, SSL, एनालिटिक्स और सर्च सेटअप हम करते हैं — साइट सिर्फ़ प्रकाशित नहीं, मापी हुई लाइव होती है।" },
    { label: "चरण 06 · साल 1", title: "होस्टिंग और सपोर्ट", body: "पहले साल की होस्टिंग, बैकअप और मानवीय सपोर्ट कोटेशन में शामिल हैं। जवाब वही इंजीनियर देता है जिसने इसे बनाया।" },
  ],
  railTitle: "एंगेजमेंट का रास्ता",
  railAlt: "आरेख: एक रेल पर छह जुड़े चरण — मुफ़्त ऑडिट, स्कोप्ड प्रस्ताव, फ़िक्स्ड कोटेशन, साप्ताहिक डेमो के साथ बिल्ड, लॉन्च, और पहले साल की होस्टिंग व सपोर्ट।",
  bestValue: "सर्वोत्तम मूल्य",
  advantagesTitle: ["वही बजट।", "उसका ज़्यादा हिस्सा आपके लिए काम करता।"],
  advantagesIntro: "जो आइटम दूसरी एजेंसियाँ कोटेशन के बाद जोड़ती हैं, वे हम पहले ही शामिल करते हैं।",
  systemEyebrow: "दोनों प्राइस लिस्ट कैसे मेल खाती हैं",
  systemTitle: ["कौन-सा टियर देता है", "कौन-सा सिस्टम।"],
  systemIntro: (site, tier, system, service) => `टियर काम का स्कोप है। सिस्टम वह है जो वह स्कोप देता है। सबसे सस्ता बिल्ड ${site} (${tier}) है; सबसे सस्ता पूरा सिस्टम ${system} (${service}) — फ़र्क़ है ऊपर जुड़े ऑटोमेशन, SEO और एनालिटिक्स का।`,
  systemFigureTitle: "टियर के साथ सिस्टम बढ़ते जाते हैं",
  systemFigureAlt: "आरेख: चार ढेर, हर टियर के लिए एक। Launch में एक वेबसाइट परत; Growth में RevSite Pro सिस्टम; Scale में AutoSell Engine और LocalDom SEO जुड़ते हैं; Enterprise डैश्ड रूपरेखा में OperateOS और GlobalScale Suite के रूप में।",
  systemsLabel: "शामिल सिस्टम",
  step1Label: "चरण 1 · मुफ़्त",
  step1Body: "कोई लागत नहीं, कोई बंधन नहीं। आप लिखित डायग्नोसिस लेकर जाते हैं — चाहे हमें चुनें या नहीं।",
  step2Label: (price) => `चरण 2 · ${price}`,
  step2Body: "सिर्फ़ तब, जब आप बिल्ड स्कोप कराना चाहें।",
  systemLink: "देखें हर सिस्टम में क्या शामिल है",
  faqTitle: ["अच्छे सवाल।", "सीधे जवाब।"],
  faqBody: "सीधे जवाब — कोई भराव नहीं। अगर आपका सवाल यहाँ नहीं है, तो ऑडिट में पूछें; हम आपके व्यवसाय से जुड़ी हर बात का जवाब देते हैं, बिना स्लाइड डेक, बिना पिच।",
  faqLink: "और सवाल हैं? ऑडिट में पूछें",
  circuitLabel: "आपका अगला अध्याय",
  footerCenter: "ज़रूरत के आधार पर। कुछ छिपा नहीं।",
  backToTop: "ऊपर जाएँ",
  motion: { pause: "मोशन रोकें", paused: "मोशन रुका है", reduced: "कम मोशन", pauseAria: "डायग्राम मोशन रोकें", resumeAria: "डायग्राम मोशन फिर शुरू करें", reducedAria: "आपके डिवाइस की प्राथमिकता के अनुसार मोशन कम है" },
};

const ZH: PricingCopy = {
  ...EN,
  home: "首页",
  edition: "Savin Group / 价格",
  heroLead: "更多系统。",
  heroAccent: "同样预算。",
  download: "下载价格表 (PDF)",
  heroNote: "价格区间以印度卢比计 · 最终报价在免费审计之后给出",
  figureTitle: "三个层级，一套系统",
  figureAlt: "示意图：等距网格上三个逐级升高的平台——Launch、Growth 和 Scale。每个平台承载的系统模块都比前一个更多：网站、自动化、商务与 CRM，信号路径从一个平台升向下一个。第四个虚线轮廓代表按需定制的 Enterprise。",
  figureCaption: ["三个层级 / 一套系统", "示意范围"],
  figureBlocks: ["网站", "自动化", "商务 / CRM"],
  figureEnterprise: "ENTERPRISE / 定制范围",
  legend: ["层级平台", "信号路径", "系统模块"],
  bandLabel: ["我们如何定价", "一句话。"],
  facts: ["按需求定价", "先做免费审计", "无隐藏费用", "以印度卢比计的起始区间"],
  chapters: ["方案", "哪个方案适合你？", "报价包含什么", "团队为何选择我们", "每个层级背后的系统", "签约之前"],
  plansTitle: ["四种工作范围。", "一种定价方式。"],
  plansIntro: "每个方案都是起始区间，而不是套餐。页面、集成与时间表在免费审计后确定——价格随需求变化，绝不随意外变化。",
  included: "区间内包含",
  extras: "免费附加项",
  scope: "范围",
  compareTitle: ["每个方案的全部内容，", "并排对比。"],
  compareIntro: "完整功能清单，每项能力一行。凡是其他机构单独收费的项目，该行会注明。",
  compareLabel: "对比方案",
  othersPrefix: "其他机构",
  rowLabels: { uptime: "可用性", storage: "存储", backups: "备份", email: "邮箱账户", cdn: "CDN 与防护", support: "优先支持", research: "关键词与市场研究", technical: "站内与技术 SEO", meta: "Meta + Schema 设置", local: "本地 SEO 与地图", content: "内容计划", cro: "转化率优化", links: "外链建设", consulting: "持续 SEO 咨询", reporting: "营收报告" },
  yes: "包含",
  no: "不包含",
  everythingIn: (tier) => `${tier} 的全部内容`,
  pickerTitle: ["四个问题。", "一个诚实的起点。"],
  pickerIntro: "按你目前所知作答。建议只是开启对话的起点，最终范围由审计决定。",
  questions: [
    { q: "你需要多少页面？", options: [{ label: "12 页以内", tier: 0 }, { label: "12 – 30", tier: 1 }, { label: "30 – 60", tier: 2 }, { label: "门户或平台", tier: 3 }] },
    { q: "你在线销售吗？", options: [{ label: "暂时不", tier: null }, { label: "线索与咨询", tier: 1 }, { label: "是，有网店", tier: 2 }] },
    { q: "有多少个门店 / 地点？", options: [{ label: "一个", tier: null }, { label: "2 – 5", tier: 2 }, { label: "很多，或多市场", tier: 3 }] },
    { q: "需要持续的 SEO 吗？", options: [{ label: "暂时不", tier: null }, { label: "需要一些", tier: 1 }, { label: "完整计划", tier: 2 }] },
  ],
  suggestion: "我们的建议",
  startingPoint: "起点，而非报价",
  defaultReason: "大多数团队从这里开始：面向转化的网站，内置线索获取、SEO 与数据分析。",
  reasons: [
    "范围明确、面向转化的网站，附基础 SEO——日后可加自动化而无需重建。",
    "网站加 WhatsApp 线索获取、标准 SEO 与数据分析——大多数成长型企业需要的形态。",
    "多门店或电商范围，含自动化、CRM 对接与进阶 SEO 计划。",
    "门户、ERP 与多市场项目通过付费探索冲刺确定范围，费用抵扣项目款。",
  ],
  seePlan: (tier) => `查看 ${tier} 方案`,
  answered: (n, total) => `已回答 ${n} / ${total}`,
  reset: "重新开始",
  quoteTitle: ["从第一次通话", "到第一年。"],
  quoteIntro: "每个方案的合作路径都相同。报价确定前不收取任何费用，确定后也不再追加。",
  steps: [
    { label: "第 01 步 · 免费", title: "营收审计", body: "45 分钟免费工作会议。无论是否合作，你都会带走一份书面诊断。" },
    { label: "第 02 步", title: "范围明确的提案", body: "页面、集成与时间表，白纸黑字。Enterprise 范围先经过付费探索冲刺。" },
    { label: "第 03 步", title: "固定报价", body: "方案区间内的一个数字。没有按小时计费，也没有中途冒出的附加项。" },
    { label: "第 04 步", title: "构建，每周演示", body: "每周都能看到可运行的软件，每个阶段验收后才进入下一阶段。" },
    { label: "第 05 步", title: "上线", body: "DNS、SSL、数据分析与搜索引擎设置由我们完成——网站带着数据上线，而不只是发布。" },
    { label: "第 06 步 · 第一年", title: "托管与支持", body: "第一年的托管、备份与人工支持都在报价之内。由构建它的工程师亲自回复。" },
  ],
  railTitle: "合作路径",
  railAlt: "示意图：同一轨道上的六个相连阶段——免费审计、范围明确的提案、固定报价、每周演示的构建、上线，以及第一年的托管与支持。",
  bestValue: "最佳价值",
  advantagesTitle: ["同样预算。", "更多为你所用。"],
  advantagesIntro: "其他机构在报价之后追加的项目，正是我们在报价之前就已内置的项目。",
  systemEyebrow: "两份价格表如何对应",
  systemTitle: ["哪个层级对应", "哪套系统。"],
  systemIntro: (site, tier, system, service) => `层级是工作范围，系统是该范围交付的成果。最低价的建站是 ${site}（${tier}）；最低价的完整系统是 ${system}（${service}）——差别在于叠加其上的自动化、SEO 与数据分析。`,
  systemFigureTitle: "系统随层级层层叠加",
  systemFigureAlt: "示意图：四个堆叠，每个层级一个。Launch 只有一层网站；Growth 是 RevSite Pro 系统；Scale 叠加 AutoSell Engine 与 LocalDom SEO；Enterprise 以虚线绘出 OperateOS 与 GlobalScale Suite。",
  systemsLabel: "包含的系统",
  step1Label: "第 1 步 · 免费",
  step1Body: "无费用、无承诺。无论是否合作，你都会带走一份书面诊断。",
  step2Label: (price) => `第 2 步 · ${price}`,
  step2Body: "仅在你希望确定项目范围时进行。",
  systemLink: "查看每套系统包含什么",
  faqTitle: ["好问题。", "直接回答。"],
  faqBody: "直接的回答，没有废话。如果没有你的问题，请在审计中提出——凡与你的业务相关，我们都会回答，没有幻灯片，也没有推销。",
  faqLink: "还有问题？在审计中提问",
  circuitLabel: "你的下一章",
  footerCenter: "按需求定价。没有隐藏项。",
  backToTop: "回到顶部",
  motion: { pause: "暂停动效", paused: "动效已暂停", reduced: "减弱动效", pauseAria: "暂停图示动效", resumeAria: "恢复图示动效", reducedAria: "已根据设备偏好减弱动效" },
};

const GU: PricingCopy = {
  ...EN,
  home: "હોમ",
  edition: "Savin Group / પ્રાઇસિંગ",
  heroLead: "વધુ સિસ્ટમ.",
  heroAccent: "એ જ બજેટ.",
  download: "પ્રાઇસ શીટ ડાઉનલોડ કરો (PDF)",
  heroNote: "રેન્જ INR માં · અંતિમ ક્વોટ મફત ઓડિટ પછી",
  figureTitle: "ત્રણ ટિયર, એક સિસ્ટમ",
  figureAlt: "આકૃતિ: આઇસોમેટ્રિક ગ્રિડ પર ત્રણ ઉપર ચઢતા પ્લેટફોર્મ — Launch, Growth અને Scale. દરેક પાછલા કરતાં વધુ સિસ્ટમ બ્લોક ધરાવે છે — સાઇટ, પછી ઓટોમેશન, પછી કોમર્સ અને CRM — અને સિગ્નલ પાથ એક પ્લેટફોર્મથી બીજા સુધી ઉપર જાય છે. ચોથી ડૅશ્ડ રૂપરેખા Enterprise દર્શાવે છે.",
  figureCaption: ["ત્રણ ટિયર / એક સિસ્ટમ", "ઉદાહરણરૂપ સ્કોપ"],
  figureBlocks: ["સાઇટ", "ઓટોમેશન", "કોમર્સ / CRM"],
  figureEnterprise: "ENTERPRISE / કસ્ટમ સ્કોપ",
  legend: ["ટિયર પ્લેટફોર્મ", "સિગ્નલ પાથ", "સિસ્ટમ બ્લોક"],
  bandLabel: ["અમે કિંમત કેવી રીતે નક્કી કરીએ", "એક લીટીમાં."],
  facts: ["જરૂરિયાત આધારિત", "પહેલા મફત ઓડિટ", "કોઈ છુપી કિંમત નહીં", "INR માં શરૂઆતી રેન્જ"],
  chapters: ["પ્લાન", "કયો પ્લાન યોગ્ય છે?", "ક્વોટમાં શું શામેલ છે", "ટીમો અમને કેમ પસંદ કરે છે", "દરેક ટિયર પાછળની સિસ્ટમ", "સાઇન કરતાં પહેલાં"],
  plansTitle: ["ચાર પ્રકારનું કામ.", "કિંમત નક્કી કરવાની એક રીત."],
  plansIntro: "દરેક પ્લાન શરૂઆતી રેન્જ છે, પેકેજ નહીં. પેજ, ઇન્ટિગ્રેશન અને સમયરેખા મફત ઓડિટ પછી નક્કી થાય છે — કિંમત જરૂરિયાત સાથે બદલાય છે, ક્યારેય સરપ્રાઇઝ સાથે નહીં.",
  included: "રેન્જમાં શામેલ",
  extras: "મફત એક્સ્ટ્રા",
  scope: "સ્કોપ",
  compareTitle: ["દરેક પ્લાનની દરેક વસ્તુ,", "સામસામે."],
  compareIntro: "સંપૂર્ણ ફીચર યાદી, દરેક ક્ષમતા માટે એક પંક્તિ. જ્યાં બીજી એજન્સીઓ અલગથી બિલ કરે છે, ત્યાં પંક્તિમાં લખેલું છે.",
  compareLabel: "પ્લાન સરખાવો",
  othersPrefix: "અન્ય",
  rowLabels: { uptime: "અપટાઇમ", storage: "સ્ટોરેજ", backups: "બેકઅપ", email: "ઈમેઇલ એકાઉન્ટ", cdn: "CDN અને સુરક્ષા", support: "પ્રાયોરિટી સપોર્ટ", research: "કીવર્ડ અને માર્કેટ રિસર્ચ", technical: "ઓન-પેજ અને ટેક્નિકલ SEO", meta: "Meta + Schema સેટઅપ", local: "લોકલ SEO અને Maps", content: "કન્ટેન્ટ પ્રોગ્રામ", cro: "કન્વર્ઝન-રેટ ઑપ્ટિમાઇઝેશન", links: "લિંક બિલ્ડિંગ", consulting: "સતત SEO સલાહ", reporting: "રેવન્યુ રિપોર્ટિંગ" },
  yes: "શામેલ",
  no: "શામેલ નથી",
  everythingIn: (tier) => `${tier} માં બધું`,
  pickerTitle: ["ચાર સવાલ.", "એક પ્રામાણિક શરૂઆત."],
  pickerIntro: "આજે જે ખબર છે તે જવાબ આપો. સૂચન વાતચીતની શરૂઆત છે — અંતિમ સ્કોપ ઓડિટ નક્કી કરે છે.",
  questions: [
    { q: "તમને કેટલાં પેજ જોઈએ?", options: [{ label: "12 સુધી", tier: 0 }, { label: "12 – 30", tier: 1 }, { label: "30 – 60", tier: 2 }, { label: "પોર્ટલ કે પ્લેટફોર્મ", tier: 3 }] },
    { q: "શું તમે ઓનલાઇન વેચો છો?", options: [{ label: "હજી નહીં", tier: null }, { label: "લીડ અને પૂછપરછ", tier: 1 }, { label: "હા, સ્ટોર", tier: 2 }] },
    { q: "કેટલી લોકેશન?", options: [{ label: "એક", tier: null }, { label: "2 – 5", tier: 2 }, { label: "ઘણી, કે અનેક બજાર", tier: 3 }] },
    { q: "શું સતત SEO જોઈએ?", options: [{ label: "હજી નહીં", tier: null }, { label: "થોડું", tier: 1 }, { label: "પૂરો પ્રોગ્રામ", tier: 2 }] },
  ],
  suggestion: "અમારું સૂચન",
  startingPoint: "શરૂઆતી બિંદુ, ક્વોટ નહીં",
  defaultReason: "મોટા ભાગની ટીમો અહીંથી શરૂ કરે છે: લીડ કૅપ્ચર, SEO અને એનાલિટિક્સ સાથેની કન્વર્ઝન-ટ્યુન્ડ સાઇટ.",
  reasons: [
    "પાયાના SEO સાથે સ્કોપ્ડ, કન્વર્ઝન-ટ્યુન્ડ સાઇટ — ઓટોમેશન પછીથી રીબિલ્ડ વગર ઉમેરો.",
    "સાઇટ સાથે WhatsApp લીડ કૅપ્ચર, સ્ટાન્ડર્ડ SEO અને એનાલિટિક્સ — વધતા વ્યવસાયોની સામાન્ય જરૂરિયાત.",
    "ઓટોમેશન, CRM વાયરિંગ અને એડવાન્સ SEO પ્રોગ્રામ સાથે મલ્ટી-લોકેશન કે ઈ-કોમર્સ સ્કોપ.",
    "પોર્ટલ, ERP અને મલ્ટી-માર્કેટ બિલ્ડ પેઇડ ડિસ્કવરી સ્પ્રિન્ટથી સ્કોપ થાય છે, જે બિલ્ડમાં સરભર થાય છે.",
  ],
  seePlan: (tier) => `${tier} પ્લાન જુઓ`,
  answered: (n, total) => `${total} માંથી ${n} ના જવાબ આપ્યા`,
  reset: "ફરીથી શરૂ કરો",
  quoteTitle: ["પહેલા કૉલથી", "પહેલા વર્ષ સુધી."],
  quoteIntro: "દરેક પ્લાન માટે માર્ગ એક જ છે. ક્વોટ નક્કી થાય તે પહેલાં કંઈ બિલ થતું નથી, અને પછી કંઈ ઉમેરાતું નથી.",
  steps: [
    { label: "પગલું 01 · મફત", title: "રેવન્યુ ઓડિટ", body: "45 મિનિટનું મફત વર્કિંગ સેશન. તમે લેખિત નિદાન લઈને જાઓ છો — અમને પસંદ કરો કે ન કરો." },
    { label: "પગલું 02", title: "સ્કોપ્ડ પ્રસ્તાવ", body: "પેજ, ઇન્ટિગ્રેશન અને સમયરેખા, લેખિતમાં. Enterprise સ્કોપ પહેલા પેઇડ ડિસ્કવરી સ્પ્રિન્ટમાંથી પસાર થાય છે." },
    { label: "પગલું 03", title: "ફિક્સ્ડ ક્વોટ", body: "પ્લાનની રેન્જમાં એક આંકડો. કલાકનું મીટર નહીં, વચ્ચે મળતાં ઍડ-ઑન નહીં." },
    { label: "પગલું 04", title: "સાપ્તાહિક ડેમો સાથે બિલ્ડ", body: "દર અઠવાડિયે ચાલતું સોફ્ટવેર જુઓ અને આગલા તબક્કા પહેલાં દરેક તબક્કો મંજૂર કરો." },
    { label: "પગલું 05", title: "લોન્ચ", body: "DNS, SSL, એનાલિટિક્સ અને સર્ચ સેટઅપ અમે કરીએ છીએ — સાઇટ માત્ર પ્રકાશિત નહીં, માપેલી લાઇવ થાય છે." },
    { label: "પગલું 06 · વર્ષ 1", title: "હોસ્ટિંગ અને સપોર્ટ", body: "પહેલા વર્ષની હોસ્ટિંગ, બેકઅપ અને માનવીય સપોર્ટ ક્વોટમાં શામેલ છે. જવાબ એ જ એન્જિનિયર આપે છે જેણે તે બનાવ્યું." },
  ],
  railTitle: "એન્ગેજમેન્ટનો માર્ગ",
  railAlt: "આકૃતિ: એક રેલ પર છ જોડાયેલા તબક્કા — મફત ઓડિટ, સ્કોપ્ડ પ્રસ્તાવ, ફિક્સ્ડ ક્વોટ, સાપ્તાહિક ડેમો સાથે બિલ્ડ, લોન્ચ, અને પહેલા વર્ષની હોસ્ટિંગ અને સપોર્ટ.",
  bestValue: "શ્રેષ્ઠ મૂલ્ય",
  advantagesTitle: ["એ જ બજેટ.", "તેનો વધુ ભાગ તમારા માટે કામ કરે."],
  advantagesIntro: "જે આઇટમ બીજી એજન્સીઓ ક્વોટ પછી ઉમેરે છે, તે અમે પહેલેથી શામેલ કરીએ છીએ.",
  systemEyebrow: "બંને પ્રાઇસ લિસ્ટ કેવી રીતે મેળ ખાય છે",
  systemTitle: ["કયો ટિયર આપે છે", "કઈ સિસ્ટમ."],
  systemIntro: (site, tier, system, service) => `ટિયર કામનો સ્કોપ છે. સિસ્ટમ તે છે જે તે સ્કોપ આપે છે. સૌથી સસ્તું બિલ્ડ ${site} (${tier}) છે; સૌથી સસ્તી પૂરી સિસ્ટમ ${system} (${service}) — તફાવત ઉપર ઉમેરાયેલા ઓટોમેશન, SEO અને એનાલિટિક્સનો છે.`,
  systemFigureTitle: "ટિયર સાથે સિસ્ટમ વધતી જાય છે",
  systemFigureAlt: "આકૃતિ: ચાર થપ્પી, દરેક ટિયર માટે એક. Launch માં એક વેબસાઇટ સ્તર; Growth માં RevSite Pro સિસ્ટમ; Scale માં AutoSell Engine અને LocalDom SEO ઉમેરાય છે; Enterprise ડૅશ્ડ રૂપરેખામાં OperateOS અને GlobalScale Suite તરીકે.",
  systemsLabel: "શામેલ સિસ્ટમ",
  step1Label: "પગલું 1 · મફત",
  step1Body: "કોઈ ખર્ચ નહીં, કોઈ બંધન નહીં. તમે લેખિત નિદાન લઈને જાઓ છો — અમને પસંદ કરો કે ન કરો.",
  step2Label: (price) => `પગલું 2 · ${price}`,
  step2Body: "ફક્ત ત્યારે, જ્યારે તમે બિલ્ડ સ્કોપ કરાવવા માંગો.",
  systemLink: "જુઓ દરેક સિસ્ટમમાં શું શામેલ છે",
  faqTitle: ["સારા સવાલ.", "સીધા જવાબ."],
  faqBody: "સીધા જવાબ — કોઈ ભરાવો નહીં. તમારો સવાલ અહીં ન હોય તો ઓડિટમાં પૂછો; અમે તમારા વ્યવસાયને લગતી દરેક વાતનો જવાબ આપીએ છીએ, સ્લાઇડ ડેક વગર, પિચ વગર.",
  faqLink: "હજી સવાલ છે? ઓડિટમાં પૂછો",
  circuitLabel: "તમારો આગલો અધ્યાય",
  footerCenter: "જરૂરિયાત આધારિત. કંઈ છુપું નહીં.",
  backToTop: "ઉપર જાઓ",
  motion: { pause: "મોશન રોકો", paused: "મોશન રોકાયેલું છે", reduced: "ઘટાડેલું મોશન", pauseAria: "ડાયાગ્રામ મોશન રોકો", resumeAria: "ડાયાગ્રામ મોશન ફરી શરૂ કરો", reducedAria: "તમારા ડિવાઇસની પસંદગી મુજબ મોશન ઘટાડેલું છે" },
};

const TABLE: Partial<Record<Locale, PricingCopy>> = { en: EN, es: ES, fr: FR, de: DE, ar: AR, hi: HI, zh: ZH, gu: GU };

export function getPricingCopy(locale: string): PricingCopy {
  return TABLE[locale as Locale] ?? EN;
}
