export const cityCopyEn = {
  eyebrow: "Local understanding. Connected ambition.", heroStart: "Built for", heroEnd: "Connected for what’s next.",
  intro: "Websites, AI, automation and ERP systems that connect the way your business attracts customers, makes decisions and gets work done.",
  explore: "Explore your connected business", procurement: "Explore procurement", schematic: "An illustrative business network", nodeHint: "Select the ERP node to follow a purchase", coordinates: "City coordinates",
  nav: ["Overview", "Services", "Process", "Case studies", "About", "Insights", "Contact"],
  chapters: ["The local perspective", "Your business, connected", "Built around your market", "From a conversation to a working system", "Local roots. Wider ambition.", "Questions, answered", "Build what comes next"],
  localTitle: ["Every city has a rhythm.", "Your systems should understand it."], localRead: "Read the local business context", industryLabel: "The industries shaping this market", areas: "Across the city’s business districts", areaNote: "Service coverage · schematic, not a geographic map", localFocus: "A local opportunity",
  systemTitle: ["See the handoffs.", "Then connect them."], systemIntro: "Follow the work across departments. Every request, decision and update becomes part of one connected system.",
  tabs: ["Procurement", "Sales & customers", "Operations"], systemLabel: "Explore a business workflow", demo: "Illustrative workflow", erp: "Open ERP procurement walkthrough",
  workflows: [
    { title: "One purchase. Every stage connected.", body: "Start with a purchase requisition. Follow approval, supplier quotations and a purchase order through transport planning to goods receipt.", inputs: ["Purchase request", "Supplier quotes", "Stock requirement"], outputs: ["Approved order", "Planned dispatch", "Updated inventory"], flow: ["Requisition", "Approval + RFQ", "Compare + PO", "Dispatch + receipt"], note: "Choose road, sea or air inside the walkthrough. Watch the documents and vehicles carry the process forward." },
    { title: "An enquiry becomes a relationship.", body: "Connect your website, customer conversations and CRM so every enquiry has an owner, a next action and a visible history.", inputs: ["Website enquiry", "Customer messages", "Sales context"], outputs: ["Assigned owner", "Timely follow-up", "Shared customer record"], flow: ["Capture", "Qualify", "Follow up", "Learn"], note: "Bring your existing sales tools together around the customer journey." },
    { title: "A clearer view of work in motion.", body: "Connect jobs, people and operational data. Surface the next task, flag exceptions and keep decisions attached to the records behind them.", inputs: ["Work orders", "Team updates", "Machine signals"], outputs: ["Coordinated tasks", "Exception alerts", "Operational visibility"], flow: ["Connect", "Coordinate", "Monitor", "Improve"], note: "Build around the workflow first. Add AI where it can help people take a useful next step." },
  ],
  transport: "Documents move. Logistics follows.", sampleLanguage: "Interactive walkthrough in English", stack: "The local technology stack", servicesTitle: ["The right capabilities.", "For the work in front of you."], servicesLink: "Explore services", approachTitle: ["A clear way forward.", "From context to capability."], approachIntro: "Understand the constraints. Agree the scope. Connect the systems. Keep improving with the people who use them.", operating: "How we work here", cadence: "Our working cadence", artefacts: "What you receive", localDelivery: "Delivery in this city", heritage: "The character behind the commerce", landmarks: "Places that shape the city", heritageLink: "Explore the city’s story", results: "From the local portfolio", caseLink: "Explore case studies", voices: "In our clients’ words", faqTitle: ["Before we build.", "Let’s make things clear."], related: "Connected to more Indian cities", allCities: "All cities", cta: ["Your next chapter.", "Built to work together."], ctaBody: "Tell us where work slows down, where systems disconnect, or what you want to build. We’ll explore the next useful step together.", contact: "Talk about your business", pause: "Pause motion", resume: "Resume motion", reduced: "Reduced motion",
};

export type CityCopy = typeof cityCopyEn;

const cityCopyHi: CityCopy = {
  ...cityCopyEn,
  eyebrow: "स्थानीय समझ। जुड़ी हुई संभावनाएँ।", heroStart: "के लिए बना", heroEnd: "अगले कदम के लिए जुड़े सिस्टम।",
  intro: "वेबसाइट, AI, ऑटोमेशन और ERP — ग्राहक जुड़ाव, सही निर्णय और रोज़मर्रा के काम को एक साथ जोड़ने वाले सिस्टम।",
  explore: "जुड़े हुए व्यवसाय को समझें", procurement: "खरीद प्रक्रिया देखें", schematic: "व्यवसाय नेटवर्क का उदाहरण", nodeHint: "खरीद की पूरी यात्रा देखने के लिए ERP चुनें", coordinates: "शहर के निर्देशांक",
  nav: ["परिचय", "सेवाएँ", "प्रक्रिया", "केस स्टडी", "शहर के बारे में", "लेख", "संपर्क"],
  chapters: ["स्थानीय नज़रिया", "आपका जुड़ा हुआ व्यवसाय", "आपके बाज़ार के अनुसार", "बातचीत से काम करने वाले सिस्टम तक", "स्थानीय जड़ें। बड़ी संभावनाएँ।", "आपके सवाल", "अगला कदम बनाएँ"],
  localTitle: ["हर शहर की अपनी रफ़्तार है।", "आपके सिस्टम उसे समझें।"], localRead: "स्थानीय बाज़ार को विस्तार से समझें", industryLabel: "इस बाज़ार के प्रमुख उद्योग", areas: "शहर के व्यावसायिक क्षेत्रों में", areaNote: "सेवा क्षेत्र · सांकेतिक चित्र, भौगोलिक नक्शा नहीं", localFocus: "स्थानीय अवसर",
  systemTitle: ["काम की हर कड़ी देखें।", "फिर उन्हें एक साथ जोड़ें।"], systemIntro: "हर विभाग में काम की यात्रा समझें। हर अनुरोध, निर्णय और अपडेट एक जुड़े हुए सिस्टम का हिस्सा बने।",
  tabs: ["खरीद प्रक्रिया", "बिक्री और ग्राहक", "संचालन"], systemLabel: "व्यावसायिक प्रक्रिया चुनें", demo: "प्रक्रिया का उदाहरण", erp: "ERP की पूरी खरीद प्रक्रिया खोलें",
  workflows: [
    { title: "एक खरीद। हर चरण जुड़ा हुआ।", body: "खरीद अनुरोध से शुरुआत करें। मंज़ूरी, कोटेशन और खरीद आदेश से लेकर परिवहन योजना और माल प्राप्ति तक की यात्रा देखें।", inputs: ["खरीद अनुरोध", "आपूर्तिकर्ता कोटेशन", "स्टॉक की ज़रूरत"], outputs: ["स्वीकृत खरीद आदेश", "डिस्पैच योजना", "अपडेटेड इन्वेंटरी"], flow: ["अनुरोध", "मंज़ूरी और RFQ", "तुलना और PO", "डिस्पैच और प्राप्ति"], note: "डेमो में सड़क, समुद्र या हवाई परिवहन चुनें। दस्तावेज़ों और वाहनों के साथ हर चरण को आगे बढ़ते देखें।" },
    { title: "पूछताछ से ग्राहक संबंध तक।", body: "वेबसाइट, ग्राहक बातचीत और CRM को जोड़ें ताकि हर पूछताछ का ज़िम्मेदार, अगला कदम और पूरा इतिहास स्पष्ट हो।", inputs: ["वेबसाइट पूछताछ", "ग्राहक संदेश", "बिक्री की जानकारी"], outputs: ["ज़िम्मेदार व्यक्ति", "समय पर फ़ॉलो-अप", "साझा ग्राहक रिकॉर्ड"], flow: ["दर्ज करें", "समझें", "फ़ॉलो-अप", "सीखें"], note: "ग्राहक की यात्रा के आसपास अपने मौजूदा बिक्री टूल जोड़ें।" },
    { title: "चलते हुए काम की स्पष्ट तस्वीर।", body: "काम, टीम और डेटा को जोड़ें। अगला काम सामने लाएँ, समस्याओं का संकेत दें और निर्णयों को उनके रिकॉर्ड से जोड़ें।", inputs: ["कार्य आदेश", "टीम अपडेट", "मशीन संकेत"], outputs: ["तालमेल वाले कार्य", "समस्या अलर्ट", "संचालन की स्पष्टता"], flow: ["जोड़ें", "तालमेल", "निगरानी", "सुधार"], note: "पहले प्रक्रिया को समझें। जहाँ अगला उपयोगी कदम लेने में मदद मिले, वहाँ AI जोड़ें।" },
  ],
  transport: "दस्तावेज़ से डिस्पैच तक।", sampleLanguage: "इंटरैक्टिव डेमो अंग्रेज़ी में", stack: "स्थानीय टेक्नोलॉजी स्टैक", servicesTitle: ["सही क्षमताएँ।", "आपके काम की ज़रूरतों के लिए।"], servicesLink: "सेवाएँ देखें", approachTitle: ["आगे बढ़ने का स्पष्ट रास्ता।", "समझ से समाधान तक।"], approachIntro: "ज़रूरत समझें। काम का दायरा तय करें। सिस्टम जोड़ें। उन्हें इस्तेमाल करने वाली टीम के साथ सुधार करते रहें।", operating: "यहाँ काम करने का तरीका", cadence: "हमारा कार्य क्रम", artefacts: "आपको क्या मिलेगा", localDelivery: "इस शहर में डिलीवरी", heritage: "व्यापार के पीछे शहर की पहचान", landmarks: "शहर को पहचान देने वाली जगहें", heritageLink: "शहर की कहानी जानें", results: "स्थानीय पोर्टफोलियो से", caseLink: "केस स्टडी देखें", voices: "हमारे ग्राहकों की बात", faqTitle: ["काम शुरू होने से पहले।", "हर बात स्पष्ट करें।"], related: "भारत के और शहरों से जुड़े", allCities: "सभी शहर", cta: ["आपका अगला अध्याय।", "मिलकर काम करने के लिए बना।"], ctaBody: "बताएँ कहाँ काम धीमा पड़ता है, कहाँ सिस्टम नहीं जुड़ते, या आप क्या बनाना चाहते हैं। साथ मिलकर अगला उपयोगी कदम तय करें।", contact: "अपने व्यवसाय पर बात करें", pause: "एनीमेशन रोकें", resume: "एनीमेशन चलाएँ", reduced: "कम गति",
};

// City bodies retain their existing English/Hindi fallback and indexability rules.
export function getCityCopy(locale: string): CityCopy { return locale === "hi" ? cityCopyHi : cityCopyEn; }
