import type { Locale } from "@/lib/i18n";
import { EN_ABOUT, type AboutCopy } from "./about-copy";

// Page-owned copy follows the same locale keys as the shared message catalog.
// Keep this server-side: the process explorer receives only its five steps.
const translations: Record<Exclude<Locale, "en">, AboutCopy> = {
  es: {
    technologies: [["Agentes de IA", "Analítica"], ["APIs", "Automatización", "Integraciones"], ["ERP", "CRM", "Software a medida"], ["IoT", "Máquinas", "Sensores"]],
    meta: "Conoce Sanat Dynamo: conectamos software, IA y operaciones alrededor de las personas que hacen funcionar tu negocio.",
    hero: ["Buenas empresas.", "Mejor conectadas.", "Pensadas para las personas."],
    intro: "Somos Sanat Dynamo. Unimos conocimiento del negocio e ingeniería de sistemas para que las operaciones complejas funcionen como una sola.",
    explore: "Conoce nuestra forma de pensar", blueprint: "La idea detrás del sistema",
    layers: ["Personas y propósito", "Sistemas conectados", "Resultados de negocio"],
    chapters: ["Quiénes somos", "Por qué existimos", "Nuestros principios", "Cómo trabajamos", "Nuestra filosofía tecnológica", "La transformación", "Tu próximo capítulo"],
    identity: ["Un socio de ingeniería.", "Parte de tu realidad."],
    identityBody: ["Diseñamos y conectamos software a medida, ERP, flujos de IA y sistemas industriales para fabricantes y empresas en crecimiento.", "Trabajamos junto a tu equipo. Quienes construyen el sistema conocen el proceso, revisan los traspasos y aclaran el siguiente paso."],
    teamLabel: "Integrados desde el inicio", teamTitle: "Tu negocio en el centro.", roles: ["Conocimiento del negocio", "Ingeniería de software", "Integración de sistemas"], teamNote: "Un contexto compartido. De la primera conversación al sistema en marcha.",
    why: ["Crecer añade complejidad.", "Creamos claridad."], whyBody: "Al crecer, el trabajo se acumula entre herramientas, equipos y máquinas. Cerramos esas brechas para que crecer no signifique improvisar más soluciones.", friction: ["Trabajo repetitivo", "Información dispersa", "Decisiones desconectadas"], clarity: "Claridad.", clarityNote: "La información correcta. La persona adecuada. El siguiente paso.",
    principlesTitle: ["Pocas convicciones.", "En cada decisión."], principlesIntro: "La tecnología es útil cuando mejora cómo se trabaja. Estos principios guían lo que construimos.",
    principles: [
      { title: "Automatizar lo repetitivo. Cuidar lo humano.", body: "Los sistemas realizan las tareas repetibles. Las personas se concentran en el criterio, las relaciones y las decisiones que necesitan su experiencia." },
      { title: "Conectar antes de añadir.", body: "Entender qué funciona. Unir datos y procesos antes de sumar otra herramienta que tu equipo deba gestionar." },
      { title: "La IA debe demostrar su valor.", body: "Una tarea útil, contexto relevante y permisos claros. Validación, revisión humana y resultados medibles." },
      { title: "Construir para lo que viene.", body: "Sistemas mantenibles, interfaces claras y espacio para crecer. Acordamos cómo medir el éxito: tiempo, errores o velocidad de decisión." },
    ],
    processTitle: ["Primero, el trabajo.", "Después, el sistema."], processIntro: "Una empresa conectada se construye con intención. Cada paso da una base más sólida al siguiente.", processHint: "Explora las cinco etapas", output: "Lo que obtienes",
    steps: [
      { title: "Entender", short: "Encontrar el obstáculo real.", body: "Escuchamos a quienes hacen el trabajo. Mapeamos el proceso, localizamos el cuello de botella y definimos un resultado mejor.", output: "Un problema claro y un punto de partida medible." },
      { title: "Conectar", short: "Crear un contexto compartido.", body: "Mapeamos datos, herramientas y traspasos. Conectamos los sistemas con responsables claros para la información.", output: "Un plan de integración adaptado a tu operación." },
      { title: "Automatizar", short: "Dar flujo al trabajo rutinario.", body: "Convertimos tareas repetibles en flujos definidos. Probamos excepciones y aprobaciones junto a tu equipo.", output: "Un flujo probado, con reglas y controles humanos." },
      { title: "Inteligencia", short: "Convertir contexto en acción.", body: "Incorporamos analítica o IA donde ayudan a interpretar información, preparar acciones y decidir mejor.", output: "Inteligencia útil dentro del trabajo cotidiano." },
      { title: "Escalar", short: "Mejorar lo que funciona.", body: "Comparamos resultados con el punto de partida. Refinamos, documentamos y ampliamos el sistema con tu negocio.", output: "Un sistema mantenible y una próxima mejora clara." },
    ],
    techTitle: ["Cada tecnología tiene un papel.", "Tu negocio lo define."], techIntro: "Elegimos las herramientas según el problema. Cada capa convierte información en acciones útiles y con responsables claros.",
    techLayers: [{ title: "Inteligencia", purpose: "Interpretar el contexto. Apoyar una decisión." }, { title: "Orquestación", purpose: "Mover el trabajo entre sistemas." }, { title: "Sistemas de negocio", purpose: "Dar a la operación un registro compartido." }, { title: "El mundo físico", purpose: "Conectar lo que sucede en planta." }], techNote: "Diseñado para tus procesos, permisos e infraestructura.",
    transformationTitle: ["Mejores sistemas.", "Más espacio para las personas."], transformationIntro: "El cambio se nota en un día normal: menos seguimiento manual y más claridad sobre lo que importa.", before: "El trabajo entre los sistemas", after: "El sistema junto a tu equipo", beforeLabels: ["Volver a introducir información", "Perseguir la siguiente actualización", "Decidir con una visión parcial"], afterLabels: ["Capturar una vez. Compartir el contexto.", "Dejar que el flujo impulse el trabajo.", "Ver con claridad. Decidir con confianza."], transformationNote: "Una dirección de diseño. El éxito se mide frente a tu propio punto de partida.", workLink: "Ver sistemas en la práctica",
    cta: ["Tu próximo capítulo.", "Lo construimos juntos."], ctaIntro: "Cuéntanos qué proceso requiere más esfuerzo del que debería.", auditNote: "Auditoría gratuita de {minutes} minutos. Diagnóstico escrito. Un siguiente paso claro.", servicesLink: "Explora lo que construimos",
  },
  fr: {
    technologies: [["Agents IA", "Analytique"], ["APIs", "Automatisation", "Intégrations"], ["ERP", "CRM", "Logiciels sur mesure"], ["IoT", "Machines", "Capteurs"]],
    meta: "Découvrez Sanat Dynamo : nous relions logiciels, IA et opérations autour des personnes qui font vivre votre entreprise.",
    hero: ["De bonnes entreprises.", "Mieux connectées.", "Pensées pour les personnes."], intro: "Nous sommes Sanat Dynamo. Nous allions compréhension métier et ingénierie des systèmes pour faire fonctionner ensemble des opérations complexes.", explore: "Découvrez notre approche", blueprint: "La réflexion derrière le système", layers: ["Personnes et raison d’être", "Systèmes connectés", "Résultats métier"],
    chapters: ["Qui nous sommes", "Pourquoi nous existons", "Nos convictions", "Notre méthode", "Notre philosophie technologique", "La transformation", "Votre prochain chapitre"],
    identity: ["Un partenaire d’ingénierie.", "Ancré dans votre réalité."], identityBody: ["Nous concevons et relions logiciels sur mesure, ERP, workflows d’IA et systèmes industriels pour les fabricants et les entreprises en croissance.", "Nous travaillons avec votre équipe. Les personnes qui construisent le système apprennent le processus, examinent les relais et clarifient la prochaine étape."], teamLabel: "Intégrés dès le départ", teamTitle: "Votre entreprise au centre.", roles: ["Compréhension métier", "Ingénierie logicielle", "Intégration des systèmes"], teamNote: "Un contexte commun. Du premier échange au système opérationnel.",
    why: ["La croissance complexifie.", "Nous créons de la clarté."], whyBody: "En grandissant, le travail s’accumule entre outils, équipes et machines. Nous comblons ces écarts pour éviter que la croissance multiplie les contournements.", friction: ["Travail répétitif", "Informations dispersées", "Décisions déconnectées"], clarity: "Clarté.", clarityNote: "La bonne information. La bonne personne. La prochaine étape.",
    principlesTitle: ["Quelques convictions.", "Dans chaque décision."], principlesIntro: "La technologie est utile lorsqu’elle améliore le travail. Ces principes guident nos réalisations.", principles: [
      { title: "Automatiser le répétitif. Préserver l’humain.", body: "Les systèmes traitent les tâches répétables. Les personnes se consacrent au jugement, aux relations et aux décisions qui exigent leur expérience." },
      { title: "Connecter avant d’ajouter.", body: "Comprendre ce qui fonctionne déjà. Relier données et processus avant d’ajouter un outil à gérer." },
      { title: "L’IA doit prouver son utilité.", body: "Une tâche utile, du contexte et des permissions claires. Validation, contrôle humain et résultats mesurables." },
      { title: "Construire pour la suite.", body: "Des systèmes maintenables, des interfaces claires et de la place pour grandir. Mesurer le temps gagné, les erreurs évitées ou la rapidité des décisions." },
    ], processTitle: ["D’abord, le travail.", "Ensuite, le système."], processIntro: "Une entreprise connectée se construit avec méthode. Chaque étape renforce la suivante.", processHint: "Explorez les cinq étapes", output: "Ce que vous obtenez", steps: [
      { title: "Comprendre", short: "Trouver le véritable frein.", body: "Écouter les personnes sur le terrain. Cartographier le processus, identifier le blocage et définir le résultat attendu.", output: "Un problème clair et un point de départ mesurable." },
      { title: "Connecter", short: "Créer un contexte commun.", body: "Cartographier données, outils et relais. Connecter les systèmes en précisant qui est responsable de chaque information.", output: "Un plan d’intégration adapté à votre activité." },
      { title: "Automatiser", short: "Donner un flux au travail courant.", body: "Transformer les tâches répétables en workflows. Tester exceptions et validations avec votre équipe.", output: "Un workflow testé, avec règles et contrôles humains." },
      { title: "Intelligence", short: "Transformer le contexte en action.", body: "Ajouter de l’analytique ou de l’IA là où elles facilitent l’interprétation, la préparation d’actions et la décision.", output: "Une intelligence utile au quotidien." },
      { title: "Développer", short: "Améliorer ce qui fonctionne.", body: "Comparer les résultats au point de départ. Affiner, documenter et étendre le système avec votre activité.", output: "Un système maintenable et une prochaine amélioration claire." },
    ], techTitle: ["La technologie a un rôle.", "Votre métier le définit."], techIntro: "Le problème guide le choix des outils. Chaque couche transforme l’information en actions utiles et attribuées.", techLayers: [{ title: "Intelligence", purpose: "Interpréter le contexte. Aider à décider." }, { title: "Orchestration", purpose: "Faire circuler le travail entre systèmes." }, { title: "Systèmes métier", purpose: "Partager une même référence opérationnelle." }, { title: "Le monde physique", purpose: "Connecter ce qui se passe en atelier." }], techNote: "Conçu pour vos processus, permissions et infrastructures.",
    transformationTitle: ["De meilleurs systèmes.", "Plus de place pour l’humain."], transformationIntro: "Le changement se ressent au quotidien : moins de relances et une vision plus claire de l’essentiel.", before: "Le travail entre les systèmes", after: "Le système aux côtés de l’équipe", beforeLabels: ["Saisir à nouveau l’information", "Relancer pour la prochaine mise à jour", "Décider avec une vue partielle"], afterLabels: ["Saisir une fois. Partager le contexte.", "Laisser le workflow faire avancer le travail.", "Voir clairement. Décider avec confiance."], transformationNote: "Une direction de conception. Le succès se mesure à votre propre point de départ.", workLink: "Voir des systèmes en action", cta: ["Votre prochain chapitre.", "Conçu ensemble."], ctaIntro: "Parlez-nous du processus qui demande trop d’efforts.", auditNote: "Audit gratuit de {minutes} minutes. Diagnostic écrit. Prochaine étape plus claire.", servicesLink: "Découvrez nos réalisations",
  },
  de: {
    technologies: [["KI-Agenten", "Analysen"], ["APIs", "Automatisierung", "Integrationen"], ["ERP", "CRM", "Individuelle Software"], ["IoT", "Maschinen", "Sensoren"]],
    meta: "Lernen Sie Sanat Dynamo kennen: Wir verbinden Software, KI und Abläufe rund um die Menschen in Ihrem Unternehmen.", hero: ["Gute Unternehmen.", "Besser verbunden.", "Für Menschen gebaut."], intro: "Wir sind Sanat Dynamo. Wir verbinden Geschäftsverständnis mit Systementwicklung, damit komplexe Abläufe als Ganzes funktionieren.", explore: "Unsere Denkweise kennenlernen", blueprint: "Der Gedanke hinter dem System", layers: ["Menschen und Ziele", "Verbundene Systeme", "Geschäftliche Ergebnisse"], chapters: ["Wer wir sind", "Warum es uns gibt", "Unsere Grundsätze", "Unsere Arbeitsweise", "Unsere Technologiephilosophie", "Die Veränderung", "Ihr nächstes Kapitel"],
    identity: ["Ihr Engineering-Partner.", "Teil Ihrer Arbeitswelt."], identityBody: ["Wir entwickeln und verbinden individuelle Software, ERP, KI-Workflows und industrielle Systeme für Hersteller und wachsende Unternehmen.", "Wir arbeiten mit Ihrem Team. Die Menschen, die das System entwickeln, lernen die Prozesse kennen, hinterfragen Übergaben und klären den nächsten Schritt."], teamLabel: "Von Anfang an eingebunden", teamTitle: "Ihr Unternehmen im Mittelpunkt.", roles: ["Geschäftsverständnis", "Softwareentwicklung", "Systemintegration"], teamNote: "Ein gemeinsamer Kontext. Vom ersten Gespräch bis zum laufenden System.",
    why: ["Wachstum wird komplex.", "Wir schaffen Klarheit."], whyBody: "Beim Wachsen bleibt Arbeit zwischen Werkzeugen, Teams und Maschinen liegen. Wir schließen diese Lücken, damit Wachstum weniger Behelfslösungen braucht.", friction: ["Wiederholte Aufgaben", "Verteilte Informationen", "Isolierte Entscheidungen"], clarity: "Klarheit.", clarityNote: "Die richtige Information. Die richtige Person. Der nächste Schritt.", principlesTitle: ["Wenige Überzeugungen.", "In jeder Entscheidung."], principlesIntro: "Technologie ist nützlich, wenn sie die Arbeit verbessert. Diese Grundsätze leiten unsere Entwicklung.", principles: [
      { title: "Routine automatisieren. Menschen stärken.", body: "Systeme übernehmen wiederholbare Aufgaben. Menschen konzentrieren sich auf Urteilsvermögen, Beziehungen und Entscheidungen, die Erfahrung brauchen." },
      { title: "Erst verbinden, dann ergänzen.", body: "Verstehen, was bereits funktioniert. Daten und Prozesse verbinden, bevor ein weiteres Werkzeug hinzukommt." },
      { title: "KI muss ihren Nutzen zeigen.", body: "Eine sinnvolle Aufgabe, passender Kontext und klare Berechtigungen. Validierung, menschliche Prüfung und messbare Ergebnisse." },
      { title: "Für morgen entwickeln.", body: "Wartbare Systeme, klare Schnittstellen und Raum zum Wachsen. Erfolg früh definieren: gesparte Zeit, weniger Fehler oder schnellere Entscheidungen." },
    ], processTitle: ["Zuerst die Arbeit.", "Dann das System."], processIntro: "Ein verbundenes Unternehmen entsteht bewusst. Jeder Schritt stärkt die Grundlage für den nächsten.", processHint: "Die fünf Phasen entdecken", output: "Ihr Ergebnis", steps: [
      { title: "Verstehen", short: "Den echten Engpass finden.", body: "Den Menschen zuhören, die die Arbeit leisten. Prozesse erfassen, den Engpass finden und ein besseres Ergebnis vereinbaren.", output: "Ein klares Problem und eine messbare Ausgangslage." },
      { title: "Verbinden", short: "Gemeinsamen Kontext schaffen.", body: "Daten, Werkzeuge und Übergaben erfassen. Systeme mit klaren Verantwortlichkeiten für Informationen verbinden.", output: "Ein Integrationsplan für Ihren bestehenden Betrieb." },
      { title: "Automatisieren", short: "Routine in Fluss bringen.", body: "Wiederholbare Aufgaben in definierte Abläufe übersetzen. Ausnahmen und Freigaben mit Ihrem Team testen.", output: "Ein getesteter Workflow mit Regeln und menschlichen Kontrollen." },
      { title: "Intelligenz", short: "Kontext nutzbar machen.", body: "Analysen oder KI dort ergänzen, wo sie Informationen verständlich machen, Aktionen vorbereiten und Entscheidungen unterstützen.", output: "Nützliche Intelligenz in der täglichen Arbeit." },
      { title: "Skalieren", short: "Verbessern, was funktioniert.", body: "Ergebnisse mit der Ausgangslage vergleichen. Das System verfeinern, dokumentieren und mit Ihrem Betrieb erweitern.", output: "Ein wartbares System und eine klare nächste Verbesserung." },
    ], techTitle: ["Technologie hat eine Rolle.", "Ihr Geschäft bestimmt sie."], techIntro: "Das Problem bestimmt die Werkzeuge. Jede Ebene macht Informationen zu nützlichen Handlungen mit klarer Verantwortung.", techLayers: [{ title: "Intelligenz", purpose: "Kontext verstehen. Entscheidungen unterstützen." }, { title: "Orchestrierung", purpose: "Arbeit zwischen Systemen bewegen." }, { title: "Geschäftssysteme", purpose: "Eine gemeinsame Datengrundlage schaffen." }, { title: "Die physische Welt", purpose: "Das Geschehen in der Fertigung verbinden." }], techNote: "Für Ihre Prozesse, Berechtigungen und Infrastruktur entwickelt.", transformationTitle: ["Bessere Systeme.", "Mehr Raum für Menschen."], transformationIntro: "Die Veränderung zeigt sich im Alltag: weniger Nachfragen und ein klarerer Blick auf das Wesentliche.", before: "Die Arbeit zwischen den Systemen", after: "Das System an der Seite Ihres Teams", beforeLabels: ["Informationen erneut eingeben", "Dem nächsten Update nachlaufen", "Mit einem Teilbild entscheiden"], afterLabels: ["Einmal erfassen. Kontext teilen.", "Den Workflow die Arbeit weitertragen lassen.", "Klar sehen. Sicher entscheiden."], transformationNote: "Eine Entwicklungsrichtung. Erfolg messen wir an Ihrer eigenen Ausgangslage.", workLink: "Systeme in der Praxis ansehen", cta: ["Ihr nächstes Kapitel.", "Gemeinsam entwickelt."], ctaIntro: "Erzählen Sie uns von dem Prozess, der zu viel Aufwand verlangt.", auditNote: "Kostenlose Analyse: {minutes} Minuten. Schriftliche Diagnose. Klarer nächster Schritt.", servicesLink: "Unsere Lösungen entdecken",
  },
  ar: {
    technologies: [["وكلاء الذكاء الاصطناعي", "التحليلات"], ["APIs", "الأتمتة", "التكامل"], ["ERP", "CRM", "برمجيات مخصصة"], ["IoT", "آلات", "مستشعرات"]],
    meta: "تعرّف على Sanat Dynamo: نربط البرمجيات والذكاء الاصطناعي والعمليات حول الأشخاص الذين يديرون أعمالك.", hero: ["أعمال جيدة.", "ترابط أفضل.", "تُبنى حول الإنسان."], intro: "نحن Sanat Dynamo. نجمع فهم الأعمال وهندسة الأنظمة لتعمل العمليات المعقدة كوحدة واحدة.", explore: "تعرّف على طريقة تفكيرنا", blueprint: "الفكرة وراء النظام", layers: ["الأشخاص والغاية", "أنظمة مترابطة", "نتائج الأعمال"], chapters: ["من نحن", "لماذا نعمل", "مبادئنا", "كيف نعمل", "فلسفتنا التقنية", "التحوّل", "فصلك القادم"], identity: ["شريك في الهندسة.", "جزء من عالمك."], identityBody: ["نصمم ونربط البرمجيات المخصصة وأنظمة ERP وتدفقات الذكاء الاصطناعي والأنظمة الصناعية للمصنّعين والشركات النامية.", "نعمل إلى جانب فريقك. من يبني النظام يتعرّف على العملية ويراجع نقاط التسليم ويوضح الخطوة التالية."], teamLabel: "جزء من الفريق منذ البداية", teamTitle: "أعمالك في المركز.", roles: ["فهم الأعمال", "هندسة البرمجيات", "تكامل الأنظمة"], teamNote: "سياق مشترك، من أول محادثة إلى النظام العامل.", why: ["النمو يزيد التعقيد.", "نحن نصنع الوضوح."], whyBody: "مع النمو، تتراكم الأعمال بين الأدوات والفرق والآلات. نغلق هذه الفجوات كي لا يعني النمو مزيداً من الحلول المؤقتة.", friction: ["مهام متكررة", "معلومات متفرقة", "قرارات منفصلة"], clarity: "وضوح.", clarityNote: "المعلومة الصحيحة. الشخص المناسب. الخطوة التالية.", principlesTitle: ["مبادئ قليلة.", "في كل قرار."], principlesIntro: "تكون التقنية مفيدة حين تحسّن طريقة العمل. هذه المبادئ توجّه ما نبنيه.", principles: [
      { title: "أتمتة المتكرر. تعزيز دور الإنسان.", body: "تتولى الأنظمة المهام المتكررة، ليركّز الأشخاص على التقدير والعلاقات والقرارات التي تحتاج خبرتهم." },
      { title: "الربط قبل الإضافة.", body: "نفهم ما يعمل جيداً، ونربط البيانات والعمليات قبل إضافة أداة جديدة يتعين على فريقك إدارتها." },
      { title: "على الذكاء الاصطناعي إثبات قيمته.", body: "مهمة مفيدة وسياق مناسب وصلاحيات واضحة، مع التحقق والمراجعة البشرية وقياس الأثر." },
      { title: "البناء لما هو قادم.", body: "أنظمة قابلة للصيانة وواجهات واضحة ومساحة للنمو. نتفق مبكراً على مقاييس النجاح: الوقت والأخطاء وسرعة القرار." },
    ], processTitle: ["نبدأ بالعمل.", "ثم نهندس النظام."], processIntro: "تُبنى الأعمال المترابطة بتأنٍ. كل خطوة تمنح التالية أساساً أقوى.", processHint: "استكشف المراحل الخمس", output: "ما تحصل عليه", steps: [
      { title: "الفهم", short: "تحديد العائق الحقيقي.", body: "نستمع إلى من ينفذون العمل، ونرسم العملية ونحدد الاختناق ونتفق على النتيجة الأفضل.", output: "مشكلة واضحة ونقطة بداية قابلة للقياس." },
      { title: "الربط", short: "إنشاء سياق مشترك.", body: "نرسم البيانات والأدوات ونقاط التسليم. نربط الأنظمة مع تحديد مسؤولية المعلومات المتبادلة.", output: "خطة تكامل تناسب عملياتك الحالية." },
      { title: "الأتمتة", short: "منح العمل الروتيني مساراً.", body: "نحوّل المهام المتكررة إلى تدفقات محددة، ونختبر الاستثناءات والموافقات مع فريقك.", output: "تدفق مختبر بقواعد ونقاط مراجعة بشرية." },
      { title: "الذكاء", short: "تحويل السياق إلى فعل.", body: "نضيف التحليلات أو الذكاء الاصطناعي حيث يساعدان على فهم المعلومات وإعداد الإجراءات وتحسين القرار.", output: "ذكاء مفيد ضمن العمل اليومي." },
      { title: "التوسع", short: "تحسين ما ينجح.", body: "نقارن النتائج بنقطة البداية، ونحسّن النظام ونوثقه ونوسّعه مع نمو أعمالك.", output: "نظام قابل للصيانة وتحسين تالٍ واضح." },
    ], techTitle: ["للتقنية دور.", "أعمالك تحدده."], techIntro: "نختار الأدوات حسب المشكلة. كل طبقة تحوّل المعلومات إلى إجراءات مفيدة ومسؤولة.", techLayers: [{ title: "الذكاء", purpose: "تفسير السياق ودعم القرار." }, { title: "التنسيق", purpose: "تحريك العمل بين الأنظمة." }, { title: "أنظمة الأعمال", purpose: "توفير سجل مشترك للعمليات." }, { title: "العالم المادي", purpose: "ربط ما يحدث في أرض المصنع." }], techNote: "مصمم حول عملياتك وصلاحياتك وبنيتك التحتية.", transformationTitle: ["أنظمة أفضل.", "مساحة أكبر للإنسان."], transformationIntro: "يظهر التغيير في يوم العمل العادي: متابعة يدوية أقل ورؤية أوضح لما يهم.", before: "العمل بين الأنظمة", after: "النظام يعمل مع فريقك", beforeLabels: ["إعادة إدخال المعلومات", "ملاحقة آخر تحديث", "القرار بناءً على صورة جزئية"], afterLabels: ["إدخال مرة واحدة ومشاركة السياق.", "دع التدفق يدفع العمل إلى الأمام.", "رؤية واضحة وقرار بثقة."], transformationNote: "هذا اتجاه نبني نحوه. نقيس النجاح مقارنةً بنقطة بدايتك.", workLink: "شاهد الأنظمة في التطبيق", cta: ["فصلك القادم.", "نهندسه معاً."], ctaIntro: "حدثنا عن العملية التي تتطلب جهداً أكثر مما ينبغي.", auditNote: "مراجعة مجانية لمدة {minutes} دقيقة، وتشخيص مكتوب، وخطوة تالية أوضح.", servicesLink: "استكشف ما نبنيه",
  },
  hi: {
    technologies: [["AI एजेंट", "एनालिटिक्स"], ["APIs", "स्वचालन", "इंटीग्रेशन"], ["ERP", "CRM", "कस्टम सॉफ़्टवेयर"], ["IoT", "मशीनें", "सेंसर"]],
    meta: "Sanat Dynamo को जानें: हम आपके व्यवसाय के लोगों के लिए सॉफ़्टवेयर, AI और संचालन को जोड़ते हैं।", hero: ["मज़बूत व्यवसाय।", "बेहतर जुड़ाव।", "लोगों के लिए बने।"], intro: "हम Sanat Dynamo हैं। व्यवसाय की समझ और सिस्टम इंजीनियरिंग को मिलाकर जटिल संचालन को एक साथ काम करने योग्य बनाते हैं।", explore: "हमारा नज़रिया जानें", blueprint: "सिस्टम के पीछे की सोच", layers: ["लोग और उद्देश्य", "जुड़े हुए सिस्टम", "व्यावसायिक परिणाम"], chapters: ["हम कौन हैं", "हम क्यों हैं", "हमारे सिद्धांत", "हम कैसे काम करते हैं", "तकनीक पर हमारी सोच", "बदलाव", "आपका अगला अध्याय"], identity: ["आपका इंजीनियरिंग साथी।", "आपके काम का हिस्सा।"], identityBody: ["हम निर्माताओं और बढ़ते व्यवसायों के लिए कस्टम सॉफ़्टवेयर, ERP, AI वर्कफ़्लो और औद्योगिक सिस्टम बनाते और जोड़ते हैं।", "हम आपकी टीम के साथ काम करते हैं। सिस्टम बनाने वाले लोग प्रक्रिया समझते हैं, काम के हस्तांतरण की समीक्षा करते हैं और अगला कदम स्पष्ट करते हैं।"], teamLabel: "शुरू से आपकी टीम के साथ", teamTitle: "केंद्र में आपका व्यवसाय।", roles: ["व्यवसाय की समझ", "सॉफ़्टवेयर इंजीनियरिंग", "सिस्टम इंटीग्रेशन"], teamNote: "एक साझा संदर्भ। पहली बातचीत से काम करते सिस्टम तक।", why: ["विकास जटिलता लाता है।", "हम स्पष्टता लाते हैं।"], whyBody: "व्यवसाय बढ़ता है तो टूल, टीम और मशीनों के बीच काम अटकता है। हम ये अंतर दूर करते हैं ताकि विकास के साथ अस्थायी उपाय न बढ़ें।", friction: ["दोहराया जाने वाला काम", "बिखरी जानकारी", "अलग-अलग निर्णय"], clarity: "स्पष्टता।", clarityNote: "सही जानकारी। सही व्यक्ति। सही अगला कदम।", principlesTitle: ["कुछ पक्के सिद्धांत।", "हर निर्णय में।"], principlesIntro: "तकनीक तभी उपयोगी है जब वह काम करने का तरीका बेहतर करे। हमारे निर्माण की नींव यही सिद्धांत हैं।", principles: [
      { title: "दोहराव स्वचालित करें। इंसान की भूमिका बढ़ाएँ।", body: "दोहराए जाने वाले काम सिस्टम संभालें। लोग अपने विवेक, संबंधों और अनुभव माँगने वाले निर्णयों पर ध्यान दें।" },
      { title: "नया जोड़ने से पहले मौजूदा को जोड़ें।", body: "समझें कि क्या सही चल रहा है। टीम को एक और टूल देने से पहले डेटा और प्रक्रियाओं को जोड़ें।" },
      { title: "AI की उपयोगिता साबित होनी चाहिए।", body: "उपयोगी काम, सही संदर्भ और स्पष्ट अनुमतियों से शुरू करें। जाँच, मानवीय समीक्षा और परिणामों का मापन शामिल करें।" },
      { title: "आने वाले कल के लिए बनाएँ।", body: "रखरखाव योग्य सिस्टम, स्पष्ट इंटरफ़ेस और बढ़ने की गुंजाइश। समय की बचत, कम गलतियाँ या तेज़ निर्णय जैसे माप पहले तय करें।" },
    ], processTitle: ["पहले काम समझें।", "फिर सिस्टम बनाएँ।"], processIntro: "एक जुड़ा व्यवसाय सोच-समझकर बनता है। हर चरण अगले की नींव मज़बूत करता है।", processHint: "पाँच चरण जानें", output: "आपको क्या मिलता है", steps: [
      { title: "समझें", short: "असली रुकावट पहचानें।", body: "काम करने वाले लोगों को सुनें। प्रक्रिया का नक्शा बनाएँ, रुकावट पहचानें और बेहतर परिणाम तय करें।", output: "स्पष्ट समस्या और मापने योग्य शुरुआती स्थिति।" },
      { title: "जोड़ें", short: "साझा संदर्भ बनाएँ।", body: "डेटा, टूल और हस्तांतरण समझें। जानकारी की स्पष्ट ज़िम्मेदारी के साथ सिस्टम जोड़ें।", output: "आपके मौजूदा संचालन के अनुरूप इंटीग्रेशन योजना।" },
      { title: "स्वचालन", short: "नियमित काम को प्रवाह दें।", body: "दोहराए जाने वाले काम को तय वर्कफ़्लो में बदलें। टीम के साथ अपवाद और अनुमोदन जाँचें।", output: "नियमों और मानवीय जाँच वाला परखा वर्कफ़्लो।" },
      { title: "इंटेलिजेंस", short: "संदर्भ को कार्रवाई में बदलें।", body: "जहाँ उपयोगी हो वहाँ एनालिटिक्स या AI जोड़ें ताकि जानकारी समझना, कार्रवाई तैयार करना और निर्णय लेना आसान हो।", output: "रोज़मर्रा के काम में उपयोगी इंटेलिजेंस।" },
      { title: "विस्तार", short: "जो काम करे, उसे बेहतर करें।", body: "शुरुआती स्थिति से परिणाम तुलना करें। सिस्टम सुधारें, दस्तावेज़ बनाएँ और व्यवसाय के साथ बढ़ाएँ।", output: "रखरखाव योग्य सिस्टम और अगला स्पष्ट सुधार।" },
    ], techTitle: ["तकनीक की एक भूमिका है।", "आपका व्यवसाय उसे तय करता है।"], techIntro: "हम समस्या के अनुसार टूल चुनते हैं। हर परत जानकारी को उपयोगी और ज़िम्मेदार कार्रवाई में बदलती है।", techLayers: [{ title: "इंटेलिजेंस", purpose: "संदर्भ समझें। निर्णय में मदद करें।" }, { title: "समन्वय", purpose: "सिस्टम के बीच काम आगे बढ़ाएँ।" }, { title: "व्यावसायिक सिस्टम", purpose: "संचालन को साझा रिकॉर्ड दें।" }, { title: "भौतिक दुनिया", purpose: "फ़ैक्टरी में होने वाले काम को जोड़ें।" }], techNote: "आपकी प्रक्रिया, अनुमतियों और बुनियादी ढाँचे के अनुसार बना।", transformationTitle: ["बेहतर सिस्टम।", "लोगों के लिए अधिक जगह।"], transformationIntro: "बदलाव रोज़मर्रा के काम में दिखता है: कम पीछा करना और ज़रूरी बातों की साफ़ समझ।", before: "सिस्टम के बीच का काम", after: "आपकी टीम के साथ काम करता सिस्टम", beforeLabels: ["जानकारी दोबारा दर्ज करना", "अगले अपडेट के लिए पूछते रहना", "अधूरी तस्वीर पर निर्णय लेना"], afterLabels: ["एक बार दर्ज करें। संदर्भ साझा करें।", "वर्कफ़्लो को काम आगे बढ़ाने दें।", "स्पष्ट देखें। भरोसे से निर्णय लें।"], transformationNote: "हम इस दिशा में निर्माण करते हैं। सफलता आपकी शुरुआती स्थिति से मापी जाती है।", workLink: "काम करते सिस्टम देखें", cta: ["आपका अगला अध्याय।", "मिलकर बनाएँ।"], ctaIntro: "उस प्रक्रिया के बारे में बताएँ जिसमें ज़रूरत से ज़्यादा मेहनत लगती है।", auditNote: "{minutes} मिनट का निःशुल्क ऑडिट। लिखित निदान। अगला स्पष्ट कदम।", servicesLink: "हम क्या बनाते हैं, जानें",
  },
  gu: {
    technologies: [["AI એજન્ટ", "એનાલિટિક્સ"], ["APIs", "સ્વચાલન", "એકીકરણ"], ["ERP", "CRM", "કસ્ટમ સૉફ્ટવેર"], ["IoT", "મશીનો", "સેન્સર"]],
    meta: "Sanat Dynamo વિશે જાણો: અમે તમારા વ્યવસાયના લોકો માટે સૉફ્ટવેર, AI અને કામગીરીને જોડીએ છીએ.", hero: ["મજબૂત વ્યવસાય.", "વધુ સારું જોડાણ.", "લોકો માટે રચાયેલ."], intro: "અમે Sanat Dynamo છીએ. વ્યવસાયની સમજ અને સિસ્ટમ એન્જિનિયરિંગને જોડીને જટિલ કામગીરીને એક સાથે કામ કરતી બનાવીએ છીએ.", explore: "અમારો અભિગમ જાણો", blueprint: "સિસ્ટમ પાછળનો વિચાર", layers: ["લોકો અને હેતુ", "જોડાયેલી સિસ્ટમો", "વ્યવસાયિક પરિણામો"], chapters: ["અમે કોણ છીએ", "અમારો હેતુ", "અમારા સિદ્ધાંતો", "અમારી કાર્યપદ્ધતિ", "ટેકનોલોજી પ્રત્યેનો અભિગમ", "પરિવર્તન", "તમારું આગલું પ્રકરણ"], identity: ["તમારા એન્જિનિયરિંગ સાથી.", "તમારા કામનો ભાગ."], identityBody: ["અમે ઉત્પાદકો અને વિકસતા વ્યવસાયો માટે કસ્ટમ સૉફ્ટવેર, ERP, AI વર્કફ્લો અને ઔદ્યોગિક સિસ્ટમો બનાવીએ અને જોડીએ છીએ.", "અમે તમારી ટીમ સાથે કામ કરીએ છીએ. સિસ્ટમ બનાવનારા લોકો પ્રક્રિયા સમજે છે, હસ્તાંતરણ તપાસે છે અને આગળનું પગલું સ્પષ્ટ કરે છે."], teamLabel: "શરૂઆતથી તમારી ટીમ સાથે", teamTitle: "કેન્દ્રમાં તમારો વ્યવસાય.", roles: ["વ્યવસાયની સમજ", "સૉફ્ટવેર એન્જિનિયરિંગ", "સિસ્ટમ એકીકરણ"], teamNote: "એક સહિયારો સંદર્ભ. પ્રથમ વાતચીતથી કાર્યરત સિસ્ટમ સુધી.", why: ["વિકાસ જટિલતા લાવે છે.", "અમે સ્પષ્ટતા લાવીએ છીએ."], whyBody: "વ્યવસાય વધે ત્યારે સાધનો, ટીમો અને મશીનો વચ્ચે કામ અટકે છે. અમે આ અંતર દૂર કરીએ છીએ જેથી વિકાસ સાથે કામચલાઉ ઉપાયો ન વધે.", friction: ["પુનરાવર્તિત કામ", "વિખરાયેલી માહિતી", "અલગ અલગ નિર્ણયો"], clarity: "સ્પષ્ટતા.", clarityNote: "યોગ્ય માહિતી. યોગ્ય વ્યક્તિ. યોગ્ય આગલું પગલું.", principlesTitle: ["થોડા દૃઢ સિદ્ધાંતો.", "દરેક નિર્ણયમાં."], principlesIntro: "ટેકનોલોજી ત્યારે ઉપયોગી બને છે જ્યારે કામ કરવાની રીત સુધરે. આ સિદ્ધાંતો અમારા કામનો આધાર છે.", principles: [
      { title: "પુનરાવર્તન સ્વચાલિત કરો. માનવીય ભૂમિકા વધારો.", body: "પુનરાવર્તિત કામ સિસ્ટમ સંભાળે. લોકો વિવેક, સંબંધો અને અનુભવ માગતા નિર્ણયો પર ધ્યાન આપે." },
      { title: "નવું ઉમેરતાં પહેલાં જોડો.", body: "શું સારું ચાલે છે તે સમજો. ટીમને વધુ એક સાધન આપતાં પહેલાં માહિતી અને પ્રક્રિયાઓ જોડો." },
      { title: "AIએ ઉપયોગિતા સાબિત કરવી જોઈએ.", body: "ઉપયોગી કાર્ય, યોગ્ય સંદર્ભ અને સ્પષ્ટ પરવાનગીઓથી શરૂ કરો. ચકાસણી, માનવીય સમીક્ષા અને પરિણામનું માપન સામેલ કરો." },
      { title: "આવતીકાલ માટે બનાવો.", body: "જાળવણીયોગ્ય સિસ્ટમો, સ્પષ્ટ ઇન્ટરફેસ અને વિકાસની જગ્યા. સમયની બચત, ઓછી ભૂલો કે ઝડપી નિર્ણયો જેવા માપ અગાઉ નક્કી કરો." },
    ], processTitle: ["પહેલાં કામ સમજો.", "પછી સિસ્ટમ બનાવો."], processIntro: "જોડાયેલ વ્યવસાય વિચારપૂર્વક બને છે. દરેક તબક્કો આગળના તબક્કાનો પાયો મજબૂત કરે છે.", processHint: "પાંચ તબક્કા જાણો", output: "તમને શું મળે છે", steps: [
      { title: "સમજો", short: "સાચો અવરોધ શોધો.", body: "કામ કરનારા લોકોને સાંભળો. પ્રક્રિયાનો નકશો બનાવો, અવરોધ શોધો અને સારું પરિણામ નક્કી કરો.", output: "સ્પષ્ટ સમસ્યા અને માપી શકાય તેવી શરૂઆત." },
      { title: "જોડો", short: "સહિયારો સંદર્ભ બનાવો.", body: "માહિતી, સાધનો અને હસ્તાંતરણ સમજો. માહિતીની સ્પષ્ટ જવાબદારી સાથે સિસ્ટમો જોડો.", output: "તમારી વર્તમાન કામગીરી માટે એકીકરણ યોજના." },
      { title: "સ્વચાલન", short: "નિયમિત કામને પ્રવાહ આપો.", body: "પુનરાવર્તિત કાર્યોને નક્કી વર્કફ્લોમાં ફેરવો. ટીમ સાથે અપવાદ અને મંજૂરી તપાસો.", output: "નિયમો અને માનવીય ચકાસણીવાળો પરીક્ષિત વર્કફ્લો." },
      { title: "બુદ્ધિમત્તા", short: "સંદર્ભને કાર્યમાં ફેરવો.", body: "જ્યાં ઉપયોગી હોય ત્યાં એનાલિટિક્સ અથવા AI ઉમેરો જેથી માહિતી સમજવી અને નિર્ણય લેવો સરળ બને.", output: "રોજિંદા કામમાં ઉપયોગી બુદ્ધિમત્તા." },
      { title: "વિસ્તાર", short: "જે ચાલે છે તેને સુધારો.", body: "શરૂઆત સામે પરિણામો સરખાવો. સિસ્ટમ સુધારો, દસ્તાવેજ બનાવો અને વ્યવસાય સાથે વિસ્તારો.", output: "જાળવણીયોગ્ય સિસ્ટમ અને આગળનો સ્પષ્ટ સુધારો." },
    ], techTitle: ["ટેકનોલોજીની ભૂમિકા છે.", "તમારો વ્યવસાય તે નક્કી કરે છે."], techIntro: "સમસ્યા પ્રમાણે સાધનો પસંદ કરીએ છીએ. દરેક સ્તર માહિતીને ઉપયોગી અને જવાબદાર કાર્યમાં ફેરવે છે.", techLayers: [{ title: "બુદ્ધિમત્તા", purpose: "સંદર્ભ સમજો. નિર્ણયમાં મદદ કરો." }, { title: "સંકલન", purpose: "સિસ્ટમો વચ્ચે કામ આગળ વધારો." }, { title: "વ્યવસાયિક સિસ્ટમો", purpose: "કામગીરીને સહિયારો રેકોર્ડ આપો." }, { title: "ભૌતિક દુનિયા", purpose: "ફેક્ટરીમાં થતી કામગીરી જોડો." }], techNote: "તમારી પ્રક્રિયા, પરવાનગીઓ અને માળખા અનુસાર રચાયેલ.", transformationTitle: ["વધુ સારી સિસ્ટમો.", "લોકો માટે વધુ અવકાશ."], transformationIntro: "ફેરફાર રોજિંદા કામમાં દેખાય છે: ઓછી પૂછપરછ અને જરૂરી બાબતોની સ્પષ્ટ સમજ.", before: "સિસ્ટમો વચ્ચેનું કામ", after: "તમારી ટીમ સાથે કામ કરતી સિસ્ટમ", beforeLabels: ["માહિતી ફરી દાખલ કરવી", "આગળના અપડેટ માટે પૂછતા રહેવું", "અધૂરી માહિતીથી નિર્ણય લેવો"], afterLabels: ["એક વાર દાખલ કરો. સંદર્ભ વહેંચો.", "વર્કફ્લોને કામ આગળ વધારવા દો.", "સ્પષ્ટ જુઓ. વિશ્વાસથી નિર્ણય લો."], transformationNote: "અમે આ દિશામાં બનાવીએ છીએ. સફળતા તમારી શરૂઆતની સ્થિતિ સામે માપીએ છીએ.", workLink: "કાર્યરત સિસ્ટમો જુઓ", cta: ["તમારું આગલું પ્રકરણ.", "સાથે મળીને બનાવીએ."], ctaIntro: "એવી પ્રક્રિયા વિશે જણાવો જેમાં જરૂર કરતાં વધુ મહેનત લાગે છે.", auditNote: "{minutes} મિનિટનું નિઃશુલ્ક ઑડિટ. લેખિત નિદાન. આગળનું સ્પષ્ટ પગલું.", servicesLink: "અમે શું બનાવીએ છીએ તે જાણો",
  },
  zh: {
    technologies: [["AI 智能体", "分析"], ["APIs", "自动化", "集成"], ["ERP", "CRM", "定制软件"], ["IoT", "机器", "传感器"]],
    meta: "了解 Sanat Dynamo：我们以企业中的人为中心，连接软件、AI 与业务运营。", hero: ["优秀的企业。", "更好的连接。", "围绕人来构建。"], intro: "我们是 Sanat Dynamo。我们将业务理解与系统工程相结合，让复杂的运营协同运转。", explore: "了解我们的思考方式", blueprint: "系统背后的思考", layers: ["人与目标", "互联的系统", "业务成果"], chapters: ["我们是谁", "我们为何存在", "我们的原则", "我们如何工作", "技术理念", "业务转变", "您的下一篇章"], identity: ["您的工程伙伴。", "融入您的工作。"], identityBody: ["我们为制造商和成长型企业设计并连接定制软件、ERP、AI 工作流和工业系统。", "我们与您的团队并肩工作。构建系统的人了解业务流程，审视交接环节，并明确下一步。"], teamLabel: "从一开始就融入团队", teamTitle: "以您的业务为中心。", roles: ["业务理解", "软件工程", "系统集成"], teamNote: "共享同一背景，从第一次沟通到系统投入运行。", why: ["增长带来复杂性。", "我们带来清晰。"], whyBody: "随着业务发展，工作堆积在工具、团队和机器之间的空隙中。我们弥合这些空隙，让增长不再意味着更多临时应对。", friction: ["重复劳动", "分散的信息", "孤立的决策"], clarity: "清晰。", clarityNote: "正确的信息，合适的人，明确的下一步。", principlesTitle: ["几项坚定原则。", "贯穿每个决定。"], principlesIntro: "技术的价值在于改善工作方式。这些原则指导着我们的每一次构建。", principles: [
      { title: "自动化重复工作，发挥人的价值。", body: "让系统处理可重复的任务，让人专注于判断、关系以及需要经验的决策。" },
      { title: "先连接，再添加。", body: "了解现有工具的价值。在增加新工具之前，先连接数据与流程。" },
      { title: "AI 必须证明自己的价值。", body: "从有用的任务、相关背景和明确权限出发，加入验证与人工审核，并衡量实际效果。" },
      { title: "为未来做好准备。", body: "注重可维护的系统、清晰的接口和成长空间。提前约定衡量方式：节省时间、减少错误或加快决策。" },
    ], processTitle: ["先理解工作。", "再构建系统。"], processIntro: "互联的企业需要有计划地建设。每一步都为下一步奠定更坚实的基础。", processHint: "探索五个阶段", output: "您将获得", steps: [
      { title: "理解", short: "找到真正的瓶颈。", body: "倾听实际执行工作的人。梳理流程，识别瓶颈，共同定义更好的结果。", output: "明确的问题与可衡量的起点。" },
      { title: "连接", short: "建立共享背景。", body: "梳理数据、工具与交接。连接需要协作的系统，明确每项信息的责任归属。", output: "适合现有运营的集成蓝图。" },
      { title: "自动化", short: "让日常工作顺畅流动。", body: "将重复任务转为明确的工作流，与团队一起测试异常情况和审批环节。", output: "经过测试、具备规则和人工检查点的工作流。" },
      { title: "智能", short: "将背景转化为行动。", body: "在有帮助的地方加入分析或 AI，协助理解信息、准备行动并改善决策。", output: "融入日常工作、切实有用的智能能力。" },
      { title: "扩展", short: "持续改善有效的方法。", body: "对照基线评估结果，完善系统、编写文档，并随业务发展进行扩展。", output: "可维护的系统与明确的下一项改进。" },
    ], techTitle: ["技术各有其用。", "由您的业务定义。"], techIntro: "我们根据问题选择工具。每一层都服务于同一目标：将信息转化为有用、可追责的行动。", techLayers: [{ title: "智能", purpose: "理解背景，辅助决策。" }, { title: "流程编排", purpose: "让工作在系统之间流动。" }, { title: "业务系统", purpose: "为运营提供共享记录。" }, { title: "物理世界", purpose: "连接生产现场发生的事情。" }], techNote: "围绕您的流程、权限与基础设施设计。", transformationTitle: ["更好的系统。", "给人更多空间。"], transformationIntro: "变化体现在平常的工作日里：减少追问，更清楚地看到真正重要的事。", before: "填补系统之间的空隙", after: "系统与团队并肩工作", beforeLabels: ["重复录入信息", "追问下一次更新", "依据局部信息做决定"], afterLabels: ["录入一次，共享背景。", "让工作流推动下一步。", "看得清楚，决策更有信心。"], transformationNote: "这是我们的设计方向。成功以您自身的起点为基准衡量。", workLink: "了解实际系统案例", cta: ["您的下一篇章。", "共同构建。"], ctaIntro: "告诉我们，哪个流程耗费了过多精力。", auditNote: "免费 {minutes} 分钟诊断，书面分析，更明确的下一步。", servicesLink: "探索我们的解决方案",
  },
};

export function getAboutCopy(locale: Locale): AboutCopy {
  return locale === "en" ? EN_ABOUT : translations[locale];
}
