export type TransportMode = "road" | "sea" | "air";

export const PROCUREMENT_STAGES = [
  { label: "Requisition", title: "A need becomes a purchase request.", detail: "Production needs 30 drive assemblies. Stock has six. The ERP creates a requisition for the remaining 24, linked to the production requirement.", event: "PR-0241 created · 24 units requested", document: "Purchase requisition", code: "PR-0241", status: "Submitted", owner: "Production → Purchasing", duration: 6500 },
  { label: "Approval", title: "The request reaches the right person.", detail: "The department lead checks the requirement and available budget. Approval releases the request to purchasing, with a recorded decision.", event: "Budget checked · requisition approved", document: "Approval record", code: "APR-0241", status: "Approved", owner: "Department lead → Buyer", duration: 5500 },
  { label: "RFQ", title: "One requirement. Three suppliers.", detail: "Purchasing sends a request for quotation with the same specification, quantity and delivery requirement to three qualified suppliers.", event: "RFQ-0186 sent · 3 suppliers invited", document: "Request for quotation", code: "RFQ-0186", status: "Sent to suppliers", owner: "Buyer → Supplier A / B / C", duration: 6500 },
  { label: "Quotations", title: "Compare the full offer, then choose.", detail: "Quotes return to the same purchasing record. The buyer compares unit cost, promised lead time and specification compliance before selecting a supplier.", event: "3 quotations received · Supplier A selected", document: "Quotation comparison", code: "CMP-0186", status: "Selection reviewed", owner: "Suppliers → Buyer", duration: 7000 },
  { label: "Purchase order", title: "An approved order, ready to fulfil.", detail: "The selected quotation becomes a purchase order. Quantities, agreed rates, delivery terms and approvals travel together to the supplier.", event: "PO-0089 issued · supplier acknowledged", document: "Purchase order", code: "PO-0089", status: "Acknowledged", owner: "Purchasing → Supplier A", duration: 7000 },
  { label: "Dispatch plan", title: "The order becomes a shipment plan.", detail: "The logistics team allocates two pallets, confirms the pickup and books the transport. Switch modes to explore the vehicle and loading plan.", event: "SHP-0089 planned · 2 pallets allocated", document: "Shipment plan", code: "SHP-0089", status: "Ready for dispatch", owner: "Supplier → Logistics", duration: 8000 },
  { label: "In transit", title: "Physical movement. Connected updates.", detail: "Goods move along the planned route. Dispatch and arrival milestones update the same purchase order, keeping the receiving team informed.", event: "Shipment dispatched · receiving team notified", document: "Shipment tracking", code: "SHP-0089", status: "In transit", owner: "Carrier → Receiving team", duration: 9000 },
  { label: "Goods receipt", title: "The goods arrive. The loop closes.", detail: "Receiving checks all 24 units against the purchase order. After quantity and quality acceptance, the goods receipt updates inventory and links back to the original request.", event: "GRN-0058 posted · stock updated to 30 units", document: "Goods receipt note", code: "GRN-0058", status: "Received & accepted", owner: "Receiving → Inventory", duration: 6500 },
] as const;

export const TRANSPORT = {
  road: { label: "Road", vehicle: "Covered truck", load: "2 secured pallets", booking: "TRK-014", route: "Supplier warehouse → Production plant", milestone: "Pickup → Road transit → Plant gate", document: "Delivery note + packing list" },
  sea: { label: "Sea", vehicle: "Container vessel", load: "2 pallets · shared container", booking: "CONT-027", route: "Origin port → Destination port", milestone: "Container loading → Sailing → Port arrival", document: "Bill of lading + packing list" },
  air: { label: "Air", vehicle: "Cargo aircraft", load: "2 pallets · cargo allocation", booking: "AWB-063", route: "Origin terminal → Arrival terminal", milestone: "Cargo acceptance → Flight → Arrival scan", document: "Air waybill + packing list" },
} as const;
