import type { Locale } from "@/lib/i18n";

type NavigationCopy = { explore: string; cities: string; insights: string; open: string; close: string; navigation: string; browse: string; theme: string; tagline: string; global: string; overview: string; more: string; pricing: string };
export const navigationCopy: Record<Locale, NavigationCopy> = {
  en: { explore: "Explore", cities: "Cities", insights: "Insights", open: "Open menu", close: "Close menu", navigation: "Site navigation", browse: "Explore the website", theme: "Appearance & region", tagline: "AI / Automation / Connected systems", global: "India · Serving globally", overview: "Overview", more: "Explore more", pricing: "Pricing" },
  hi: { explore: "और देखें", cities: "शहर", insights: "लेख", open: "मेनू खोलें", close: "मेनू बंद करें", navigation: "वेबसाइट नेविगेशन", browse: "वेबसाइट देखें", theme: "थीम और क्षेत्र", tagline: "AI / ऑटोमेशन / जुड़े हुए सिस्टम", global: "भारत · वैश्विक सेवाएँ", overview: "परिचय", more: "और जानें", pricing: "मूल्य" },
  gu: { explore: "વધુ જુઓ", cities: "શહેરો", insights: "લેખો", open: "મેનુ ખોલો", close: "મેનુ બંધ કરો", navigation: "વેબસાઇટ નેવિગેશન", browse: "વેબસાઇટ જુઓ", theme: "થીમ અને પ્રદેશ", tagline: "AI / ઓટોમેશન / જોડાયેલી સિસ્ટમ્સ", global: "ભારત · વૈશ્વિક સેવાઓ", overview: "પરિચય", more: "વધુ જાણો", pricing: "કિંમત" },
  es: { explore: "Explorar", cities: "Ciudades", insights: "Artículos", open: "Abrir menú", close: "Cerrar menú", navigation: "Navegación del sitio", browse: "Explorar el sitio", theme: "Apariencia y región", tagline: "IA / Automatización / Sistemas conectados", global: "India · Alcance global", overview: "Visión general", more: "Descubrir más", pricing: "Precios" },
  fr: { explore: "Explorer", cities: "Villes", insights: "Articles", open: "Ouvrir le menu", close: "Fermer le menu", navigation: "Navigation du site", browse: "Explorer le site", theme: "Apparence et région", tagline: "IA / Automatisation / Systèmes connectés", global: "Inde · Portée mondiale", overview: "Vue d’ensemble", more: "En savoir plus", pricing: "Tarifs" },
  de: { explore: "Entdecken", cities: "Städte", insights: "Einblicke", open: "Menü öffnen", close: "Menü schließen", navigation: "Seitennavigation", browse: "Website erkunden", theme: "Darstellung und Region", tagline: "KI / Automatisierung / Vernetzte Systeme", global: "Indien · Weltweit tätig", overview: "Übersicht", more: "Mehr entdecken", pricing: "Preise" },
  ar: { explore: "استكشف", cities: "المدن", insights: "مقالات", open: "فتح القائمة", close: "إغلاق القائمة", navigation: "التنقل في الموقع", browse: "استكشف الموقع", theme: "المظهر والمنطقة", tagline: "ذكاء اصطناعي / أتمتة / أنظمة متصلة", global: "الهند · خدمات عالمية", overview: "نظرة عامة", more: "اكتشف المزيد", pricing: "الأسعار" },
  zh: { explore: "探索", cities: "城市", insights: "洞察", open: "打开菜单", close: "关闭菜单", navigation: "网站导航", browse: "探索网站", theme: "外观与地区", tagline: "AI / 自动化 / 互联系统", global: "印度 · 服务全球", overview: "概览", more: "了解更多", pricing: "价格" },
};
